image: registry.maki.lol/tanzu-gemfire-for-kubernetes/gemfire-controller:2.6.2
controllerImage: registry.maki.lol/tanzu-gemfire-for-kubernetes/gemfire-controller@sha256:d203a0cb956a9502bf920c51a8aeecb48327a15f6f6393652870143638369678
imagePullSecretName: regsecret