apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: blog-gemfire
  namespace: app-install
  annotations:
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order.1: "upsert after upserting blog-api"
    kapp.k14s.io/change-rule.delete-order.1: "delete before deleting blog-api"
    kapp.k14s.io/change-rule.create-order.2: "upsert after upserting gemfire-operator"
    kapp.k14s.io/change-rule.delete-order.2: "delete before deleting gemfire-operator"
spec:
  serviceAccountName: kapp
  fetch:
  - git:
      url: https://github.com/making/k8s-gitops.git
      ref: origin/main
      subPath: lemon/app/blog-gemfire
  syncPeriod: 24h
  template:
  - sops:
      age:
        privateKeysSecretRef:
          name: age-key
  - ytt:
      paths:
      - config
      valuesFrom:
      - path: credentials.yaml
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true
      delete:
        #! Force delete PVCs, since StatefulSet does not delete them
        rawOptions:
        - --apply-ignored=true