apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: demo-dsql
  namespace: app-install
  annotations:
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order.1: "upsert after upserting demo-blog"
    kapp.k14s.io/change-rule.delete-order.1: "delete before deleting demo-blog"
spec:
  serviceAccountName: kapp
  fetch:
  - git:
      url: https://github.com/making/k8s-gitops.git
      ref: origin/main
      subPath: lemon/app/demo-dsql
  - git:
      url: https://github.com/making/demo-dsql.git
      ref: origin/images
  syncPeriod: 120m
  template:
  - sops:
      age:
        privateKeysSecretRef:
          name: age-key
  - ytt:
      paths:
      - 0/config
      valuesFrom:
      - path: 0/credentials.yaml
      - path: 1/native_aarch64.yaml
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true
      delete:
        #! Force delete PVCs, since StatefulSet does not delete them
        rawOptions:
        - --apply-ignored=true