apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: entry-redis
  namespace: app-install
  annotations:
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order.1: "upsert after upserting blog-api"
    kapp.k14s.io/change-rule.delete-order.1: "delete before deleting blog-api"
    kapp.k14s.io/change-rule.create-order.2: "upsert after upserting nfs-server-provisioner"
    kapp.k14s.io/change-rule.delete-order.2: "delete before deleting nfs-server-provisioner"
spec:
  serviceAccountName: kapp
  fetch:
  - helmChart:
      name: redis
      version: 22.0.7
      repository:
        url: oci://registry-1.docker.io/bitnamicharts
  - git:
      url: https://github.com/making/k8s-gitops.git
      ref: origin/main
      subPath: lemon/app/entry-redis
  syncPeriod: 24h
  template:
  - sops:
      age:
        privateKeysSecretRef:
          name: age-key
  - helmTemplate:
      name: entry-redis
      namespace: blog
      path: "0"
      valuesFrom:
      - path: 1/helm-values.yaml
  - ytt:
      paths:
      - '-'
      - 1/config
      valuesFrom:
      - path: 1/credentials.yaml
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true
      delete:
        #! Force delete PVCs, since StatefulSet does not delete them
        rawOptions:
        - --apply-ignored=true