apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: minecraft
  namespace: app-install
  annotations:
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order.2: "upsert after upserting contour"
    kapp.k14s.io/change-rule.delete-order.2: "delete before deleting contour"
    kapp.k14s.io/change-rule.create-order.3: "upsert after upserting opentelemetry-collector"
    kapp.k14s.io/change-rule.delete-order.3: "delete before deleting opentelemetry-collector"
spec:
  serviceAccountName: kapp
  fetch:
  - helmChart:
      name: minecraft
      version: 4.23.3
      repository:
        url: https://itzg.github.io/minecraft-server-charts
  - git:
      url: https://github.com/making/k8s-gitops.git
      ref: origin/main
      subPath: lemon/app/minecraft
  syncPeriod: 24h
  template:
  - sops:
      age:
        privateKeysSecretRef:
          name: age-key
  - helmTemplate:
      name: minecraft
      namespace: minecraft
      path: "0"
      valuesFrom:
      - path: 1/helm-values.yaml
  - ytt:
      paths:
      - '-'
      - 1/config
      valuesFrom:
      - path: 1/credentials.yaml
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true
      delete:
        #! Force delete PVCs, since StatefulSet does not delete them
        rawOptions:
        - --apply-ignored=true