apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: note-api
  namespace: app-install
  annotations:
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order.1: "upsert after upserting traefik"
    kapp.k14s.io/change-rule.delete-order.1: "delete before deleting traefik"
    kapp.k14s.io/change-rule.create-order.2: "upsert after upserting opentelemetry-collector"
    kapp.k14s.io/change-rule.delete-order.2: "delete before deleting opentelemetry-collector"
spec:
  serviceAccountName: kapp
  fetch:
  - helmChart:
      name: application
      version: "6.14.0"
      repository:
        url: https://stakater.github.io/stakater-charts
  - git:
      url: https://github.com/making/k8s-gitops.git
      ref: origin/main
      subPath: lemon/app/note-api
  - git:
      url: https://github.com/categolj/note-api.git
      ref: origin/images
  syncPeriod: 10m
  template:
  - sops:
      age:
        privateKeysSecretRef:
          name: age-key
  - helmTemplate:
      name: note-api
      namespace: note
      path: "0"
      valuesFrom:
      - path: 1/helm-values.yaml
  - ytt:
      paths:
      - '-'
      - 1/config
      valuesFrom:
      - path: 1/credentials.yaml
      - path: 2/jvm_aarch64.yaml
  - kbld:
      paths:
      - '-'
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true
      delete:
        #! Force delete PVCs, since StatefulSet does not delete them
        rawOptions:
        - --apply-ignored=true