apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: note-api
  namespace: app-install
  annotations:
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order.1: "upsert after upserting contour"
    kapp.k14s.io/change-rule.delete-order.1: "delete before deleting contour"
    kapp.k14s.io/change-rule.create-order.2: "upsert after upserting servicebinding-runtime"
    kapp.k14s.io/change-rule.delete-order.2: "delete before deleting servicebinding-runtime"
    kapp.k14s.io/change-rule.create-order.3: "upsert after upserting opentelemetry-collector"
    kapp.k14s.io/change-rule.delete-order.3: "delete before deleting opentelemetry-collector"
spec:
  serviceAccountName: kapp
  fetch:
  - git:
      url: https://github.com/making/k8s-gitops.git
      ref: origin/main
      subPath: lemon/app/note-api
  - git:
      url: https://github.com/categolj/note-api.git
      ref: origin/images
  #! - helmChart:
  #!     name: postgresql
  #!     version: 16.5.0
  #!     repository:
  #!       url: oci://registry-1.docker.io/bitnamicharts
  syncPeriod: 10m
  template:
  - sops:
      age:
        privateKeysSecretRef:
          name: age-key
  #! - helmTemplate:
  #!     name: note-db
  #!     namespace: note
  #!     path: "2"
  #!     valuesFrom:
  #!     - path: 0/helm-values.yaml
  - ytt:
      paths:
      - 0/config
      #! - '-'
      valuesFrom:
      - path: 0/credentials.yaml
      - path: 0/values.yaml
      - path: 1/jvm_aarch64.yaml
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true
      delete:
        #! Force delete PVCs, since StatefulSet does not delete them
        rawOptions:
        - --apply-ignored=true