kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: inlets-exit
  namespace: raspberrypi
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: contour
    namespace: projectcontour
  hostnames:
  - raspberrypi.gw.ik.am
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - kind: Service
      name: inlets-exit
      port: 6868