#@ load("@ytt:data", "data")
apiVersion: v1
kind: Secret
metadata:
  name: ldap-ssp-config
type: Opaque
stringData:
  type: "ldap-ssp"
  ldap_url: #@ data.values.ldap_url
  ldap_password: #@ data.values.ldap_password
  ldap_username: #@ data.values.ldap_username
  ldap_base: #@ data.values.ldap_base
  sendgrid_api_key: #@ data.values.sendgrid_api_key
  ssp_external_url: #@ data.values.ssp_external_url
  otlp-logs-endpoint: #@ data.values.otlp_logs_endpoint
  otlp-logs-header-authorization: #@ data.values.otlp_logs_header_authorization
  otlp-traces-endpoint: #@ data.values.otlp_traces_endpoint
  otlp-traces-header-authorization: #@ data.values.otlp_traces_header_authorization
  otlp-metrics-endpoint: #@ data.values.otlp_metrics_endpoint
  otlp-metrics-header-authorization: #@ data.values.otlp_metrics_header_authorization
