apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-cache-xml
  namespace: blog
data:
  cache.xml: |
    <?xml version="1.0"?>
    <cache xmlns="http://geode.apache.org/schema/cache"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://geode.apache.org/schema/cache http://geode.apache.org/schema/cache/cache-1.0.xsd"
           version="1.0">
        <region name="Entry">
            <region-attributes refid="PARTITION_PERSISTENT"/>
            <index name="idx_tenant_updated_at"
                   expression="tenantId, updatedAt"
                   from-clause="/Entry"/>
        </region>
    </cache>