#@ load("@ytt:data", "data")
apiVersion: v1
kind: Service
metadata:
  name: blog-gemfire-locator-management-api
  namespace: blog
  annotations:
    projectcontour.io/upstream-protocol.tls: "7070"
spec:
  type: ClusterIP
  ports:
  - name: locator-management-api
    port: 7070
  selector:
    gemfire.vmware.com/app: blog-gemfire-locator
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: blog-gemfire-locator-management-api
  namespace: blog
spec:
  virtualhost:
    fqdn: blog-gemfire-locator.ik.am
    tls:
      secretName: projectcontour//default-tls-ik-am
    ipAllowPolicy:
    - cidr: #@ data.values.allowed_ip_cidr
      source: Remote
  routes:
  - services:
    - name: blog-gemfire-locator-management-api
      port: 7070
      validation:
        caSecret: blog-gemfire-cert
        subjectName: blog-gemfire-locator.blog.svc.cluster.local