apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: entry-api
  namespace: app-install
  annotations:
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order.1: "upsert after upserting blog-ns"
    kapp.k14s.io/change-rule.delete-order.1: "delete before deleting blog-ns"
    kapp.k14s.io/change-rule.create-order.2: "upsert after upserting entry-gemfire"
    kapp.k14s.io/change-rule.delete-order.2: "delete before deleting entry-gemfire"
spec:
  serviceAccountName: kapp
  fetch:
  - helmChart:
      name: application
      version: "6.14.0"
      repository:
        url: https://stakater.github.io/stakater-charts
  - git:
      url: https://github.com/making/k8s-gitops.git
      ref: origin/main
      subPath: apricot/app/entry-api
  - git:
      url: https://github.com/categolj/entry-api-gemfire.git
      ref: origin/images
  syncPeriod: 24h
  template:
  - sops:
      age:
        privateKeysSecretRef:
          name: age-key
  - helmTemplate:
      name: entry-api
      namespace: blog
      path: "0"
      valuesFrom:
      - path: 1/helm-values.yaml
      - path: 2/jvm_aarch64.yaml
  - ytt:
      paths:
      - "-"
      - 1/config
      valuesFrom:
      - path: 1/credentials.yaml
  - kbld:
      paths:
      - '-'
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true
      delete:
        #! Force delete PVCs, since StatefulSet does not delete them
        rawOptions:
        - --apply-ignored=true