apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: httpbin
  namespace: app-install
  annotations:
    kapp.k14s.io/change-group: "{name}"
    #! kapp.k14s.io/change-rule.create-order.1: "upsert after upserting contour"
    #! kapp.k14s.io/change-rule.delete-order.1: "delete before deleting contour"
spec:
  serviceAccountName: kapp
  fetch:
  - helmChart:
      name: application
      version: "6.14.0"
      repository:
        url: https://stakater.github.io/stakater-charts
  - git:
      url: https://github.com/making/k8s-gitops.git
      ref: origin/main
      subPath: apricot/app/httpbin
  syncPeriod: 600h
  template:
  - sops:
      age:
        privateKeysSecretRef:
          name: age-key
  - helmTemplate:
      name: httpbin
      namespace: default
      path: "0"
      valuesFrom:
      - path: 1/helm-values.yaml
  - kbld:
      paths:
      - '-'
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=false
      delete:
        #! Force delete PVCs, since StatefulSet does not delete them
        rawOptions:
        - --apply-ignored=true