#@ load("@ytt:data", "data")
apiVersion: v1
kind: Secret
metadata:
  name: gemfire-registry-secret
  namespace: gemfire-system
type: kubernetes.io/dockerconfigjson
stringData:
  #@yaml/text-templated-strings
  .dockerconfigjson: |-
    {
      "auths": {
        "ghcr.io": {
          "username": "(@= data.values.ghcr.username @)",
          "password": "(@= data.values.ghcr.password @)"
        }
      }
    }