tempo:
  traces:
    jaeger:
      grpc: false
      thriftBinary: false
      thriftCompact: false
      thriftHttp: false
    otlp:
      http: true
      grpc: true
ingester:
  resources:
    requests:
      memory: 256Mi
    limits:
      memory: 512Mi
  persistence:
    size: 8Gi
    storageClass: ""
distributor:
  service:
    type: ClusterIP
compactor:
  persistence:
    size: 8Gi
    storageClass: ""
querier:
  persistence:
    size: 8Gi
    storageClass: ""
vulture:
  enabled: false