apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: servicebinding-runtime
  namespace: app-install
  annotations:
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order.1: "upsert after upserting cert-manager"
    kapp.k14s.io/change-rule.delete-order.1: "delete before deleting cert-manager"
spec:
  serviceAccountName: kapp
  fetch:
  - http:
      url: https://github.com/servicebinding/runtime/releases/download/v1.0.0/servicebinding-runtime-v1.0.0.yaml
  syncPeriod: 24h
  template:
  - ytt: { }
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true