apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: contour
  namespace: app-install
  annotations:
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order.1: "upsert after upserting cluster-issuer"
    kapp.k14s.io/change-rule.delete-order.1: "delete before deleting cluster-issuer"
    kapp.k14s.io/change-rule.create-order.2: "upsert after upserting opentelemetry-collector"
    kapp.k14s.io/change-rule.delete-order.2: "delete before deleting opentelemetry-collector"
spec:
  serviceAccountName: kapp
  fetch:
  - helmChart:
      name: contour
      version: 19.5.5
      repository:
        url: oci://registry-1.docker.io/bitnamicharts
  - git:
      url: https://github.com/making/k8s-gitops.git
      ref: origin/main
      subPath: pineapple/platform/contour
  syncPeriod: 24h
  template:
  - helmTemplate:
      name: contour
      namespace: projectcontour
      path: "0"
      valuesFrom:
      - path: 1/helm-values.yaml
  - ytt:
      paths:
      - '-'
      - 1/config
      valuesFrom:
      - path: 1/credentials.yaml
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true
      delete:
        #! Force delete PVCs, since StatefulSet does not delete them
        rawOptions:
        - --apply-ignored=true