apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: harbor
  namespace: app-install
  annotations:
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order: "upsert after upserting cluster-issuer"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting cluster-issuer"
spec:
  serviceAccountName: kapp
  fetch:
  - helmChart:
      name: harbor
      version: 1.16.2
      repository:
        url: https://helm.goharbor.io
  - git:
      url: https://github.com/making/k8s-gitops.git
      ref: origin/main
      subPath: pineapple/platform/harbor
  syncPeriod: 24h
  template:
  - helmTemplate:
      name: harbor
      namespace: harbor
      path: "0"
      valuesFrom:
      - path: 1/helm-values.yaml
  - ytt:
      paths:
      - "-"
      - 1/config
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true
      delete:
        #! Force delete PVCs, since StatefulSet does not delete them
        rawOptions:
        - --apply-ignored=true