#@ load("@ytt:data", "data")
apiVersion: v1
kind: Secret
metadata:
  name: blog-db
  namespace: blog
  annotations:
    kapp.k14s.io/change-group: service
  labels:
    app: blog-db
    app.kubernetes.io/part-of: blog-api
type: servicebinding.io/postgresql
stringData:
  type: "postgresql"
  host: #@ data.values.blog_db.host
  port: #@ data.values.blog_db.port
  username: #@ data.values.blog_db.username
  password: #@ data.values.blog_db.password
  database: "blog"
  sslmode: "require"
---
apiVersion: v1
kind: Secret
metadata:
  name: job-db
  namespace: blog
  annotations:
    kapp.k14s.io/change-group: service
  labels:
    app: job-db
    app.kubernetes.io/part-of: blog-api
type: Opaque
stringData:
  url: #@ data.values.job_db.url
  username: #@ data.values.job_db.username
  password: #@ data.values.job_db.password