#@ load("@ytt:data", "data")
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: zipkin
  namespace: zipkin
spec:
  virtualhost:
    fqdn: zipkin.lemon.maki.lol
    tls:
      secretName: projectcontour/default-tls
    ipAllowPolicy:
    - cidr: #@ data.values.allowed_ip_cidr
      source: Remote
  routes:
  - conditions:
    - prefix: /
    services:
    - name: zipkin
      port: 9411