prometheus:
    url: ENC[AES256_GCM,data:Cj8n4xGmQ6aOfz2Cm2Cj0pKhYtaRkXs1Egfe,iv:g/RtBHFRapx77Q5uty0mz17U6D/S82tZnzIwaasoTJo=,tag:G0IUThNFO7X2ZMi4Gq1JFw==,type:str]
    username: ENC[AES256_GCM,data:wToHWXA=,iv:VeomRRtVDr3+gkNUQWvVW9VefwPSCctvUMQxkEXZV3Q=,tag:GEqGZ/67mxN88LcG3BopJQ==,type:str]
    password: ENC[AES256_GCM,data:dOqMJPg9HiOucCKpiS66rEeJCMCOsGZMajux7WDpWgEeQ/W4,iv:x/+z4bCw8MANsiZSUDzQiBj1T/fkLqBO1zL5oIS+wC4=,tag:Gu+poYfwSOe76EHP5VAQFw==,type:str]
prometheus_fly:
    url: ENC[AES256_GCM,data:Ygd0wa7OOQN3+u8EJwFH2fdYEIOXDAmas/X4QjJa8mvHArDT/tY=,iv:f2lkEQLQGueUXxtk/G63WM8xpW4zcpyd58wm/+wvLAY=,tag:xMmjnCRlkh+KlkhRy4KECQ==,type:str]
    token: ENC[AES256_GCM,data:6qedPjzYW5MezwX37YjtoZx3D/sIRsDrYXRQzR6G9n1stn9jialUGRJ5L2m4ntM=,iv:fKoTUgX+vhrxFf2og2Vq0TA7sXEE0VVyjvXTkuheZDM=,tag:a6CHPmhDNtnSp001bYY0ew==,type:str]
tempo:
    url: ENC[AES256_GCM,data:ezalxKFrg4WojW+vfIsFCTcc5xuag47qHjHzojMyiOMWq1M7Gj/E1z7syQ==,iv:oLHC0jX51diS0jQGklCVVVDUP9fzakglgy4afjAx64U=,tag:cYo0SmSC7ITc+WZrXZIBTg==,type:str]
    username: ENC[AES256_GCM,data:qt611g==,iv:+td3AZKuMhLJUJQKcacKSmPteH48rcZbhtJqQ0mBvAA=,tag:Cc0jw5qhzf4eifd3auCXXQ==,type:str]
    password: ENC[AES256_GCM,data:CiI4kkf7lS+bjmjR6TF9l/J/ASX0i0StJzu25P2ttQODipXKkXRKvybsB22Q9cRlHgxJDXcwn5cjKnnz/LyuCndREGUsXAHCqoD/8U56eHH4yWwnWIiNjlk0AaRhD8TMPlBEDPzRLYXuBYm0vZBPTtRPYASFIZOwp0kkhw==,iv:vaDHgrA2g3qU1+DA2u6Wp9AWB/i22yPqEu+J45aC8G0=,tag:nb9UT7+TZ7Julyw2oymjXA==,type:str]
loki:
    url: ENC[AES256_GCM,data:Ivly3ZDlnECKXGQ0obyo/NfgplnP29tQIho0cH59x4JFjAk+PCP6TjE=,iv:j8VWgKr7jFynC3UhS0TXfICAEsxLSN+6+6jMC6c9oiE=,tag:JLXb5SlN2uTWYfuek+zMvw==,type:str]
    username: ENC[AES256_GCM,data:bNtRIag=,iv:xRkvxJouV40/okFJ2jNz+7/YhC+5cSWiwosqSJszpMY=,tag:d8/S2cFSsQg+UMUjI1o4wQ==,type:str]
    password: ENC[AES256_GCM,data:9Q8fFrXK06742P5kaWudslIrA7Ky7EDBiznUciuE+9MId+PiaTgetJn++loK3STLfuP+OUXE4JufCpQs43dtlDREWkkjiUunnbBtiijzRR8Vuzmrl75KihCLgpRbu4TSLiZH0Nb+jcybNlhJvDIkJLNRY50nNnxWwEQurg==,iv:Y3hXzRM2PgLuqJ+ASECTA8uto7Zu9CjzNxmiIQl75us=,tag:63eDYN4QSWTwOjc2ajDM+Q==,type:str]
ldap:
    host: ENC[AES256_GCM,data:YnSbUm42QWhTAw==,iv:9GImbzsT/7YNmTFIRKSiQozRIS1rp+WURAZ1umFWH2c=,tag:5Rzi9ECnl83bPn6NYs3EMQ==,type:str]
    port: ENC[AES256_GCM,data:6G/+,iv:8FUtVZz8mJNycBuu3gaLtNFefmX+RBefW7K9xPGDCBk=,tag:X0LQrpCXPhfveCGJNW+74A==,type:str]
    bind_dn: ENC[AES256_GCM,data:1bW/norlQKsqMGlWxDL2lXerL7o=,iv:Ph0NSJZ/e9cKSdR2xLxWCjgthmKvwSyyT9Cvu3+qmis=,tag:pX5+EWcjh+4eYu34qUvbcQ==,type:str]
    bind_password: ENC[AES256_GCM,data:PF4xOht8P7UuCMLDICl4epeb23pZHCokYwTNriwR,iv:BNHHvB7EHBbwjVosGufK/7JDGqZMpngfBXRFBzxmPYE=,tag:QQBGcES3C0dGZ53a2QksDQ==,type:str]
    search_filter: ENC[AES256_GCM,data:XFHkx8dSEVrF+w==,iv:rrLWcIo/JHGezJo4H1NWUQVTVPijfH2X7BRedaAvWJk=,tag:M2clySNJVSbsLGL7Me1/OA==,type:str]
    search_base_dn: ENC[AES256_GCM,data:qjW4EnM0lYyPq8MFcDYUNsrAn/7d,iv:fzeTCTpglieB1uOUOdAxECq65UWCAmFRd/HUJpOCrUQ=,tag:05THyjFYKbwYGMxWdXzY9Q==,type:str]
    group_search_filter: ENC[AES256_GCM,data:1HPw6pi5fjJMgp3GKM53Uvg=,iv:nhIwsayOb3VUVX6AxoQegL+ZTGMPDF19a79W+7IfAcU=,tag:0N5vPYngXk97wUbNDoh+Rg==,type:str]
    group_search_base_dns: ENC[AES256_GCM,data:b1MAwDt2IM0qyTfZyL0C7FiRnM3s,iv:YURcRL8KX6rr/sW3rE19pIS1ozpszRzp2ZFNdSqh5tI=,tag:VK5v3FMdtZPqWKoSeXA97g==,type:str]
    admin_group_dn: ENC[AES256_GCM,data:NeBDLlT+kkyVHB7dy1Kh5gg1Ukqx0DGgf+3FELBqxQZAtkW+xEbr,iv:Y2LUmqAPUew3nl8G/D/98qPvCe9C4W4BhGIVRZ+BfUc=,tag:3ZKRHWY8CCxAQ/FrE4nh5Q==,type:str]
    viewer_group_dn: ENC[AES256_GCM,data:tNJxkDdZioAMkDgOqs3UbJnymkWDPhHNjw3A1bb7,iv:I/1d2jRiHHusMo7h6EeFl6ryRZoe64kt0Mh3diBmwU0=,tag:hrvVrV8YmWQRo5+N8zxcwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ej7fjm78n44tz3jnr6hkzhraf97egzekjfy87rfmhlnv9flwy55se0c5gz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZzl4dkMwTTZtMXJOSCtx
            aS90a3EveTVDeGRNM0Z4Q3BidUJWUUxEUGpFCjRDTkVtY3hhd2J6WG1scFova0N3
            RWRmWnh0R0kzNlJaTGpuVWYvSWNzRDgKLS0tIGtnSkMzd2tZL095Y3hmNmtsZTMv
            SElxL2xYTjQxRktETXlLZ0tISGFuazAKJq6AZUOSGGjm+uMFwD2xBomcxi90LQTJ
            lAT08LAo8q5s7hPSzBIoqFXuNygwFUi9xVmg+kk1mcz2FFFlJnA8PA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-11T16:59:29Z"
    mac: ENC[AES256_GCM,data:CPspZmn2nJ38DbVm9k5duxXpdE7h5Ka6y57d14CY/BXgbTKX9grcg1XokTsCIXcb2c2dHXkNCWivRqtkMgAw+cC+Du1g677ed8/YhZbbSVpLdAXtnM1R3z7w8NsHDJGiY/FvMX1Zj/glfs0a0p2XiCJ1DhcN1Xz3lpYmKZzEjoU=,iv:qYW8qISjEju/B/bdAt4kvWOhoAQogWvtFkdHwNopYIw=,tag:QD5NOdCedni/zjrcMZHkzw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
