prometheus:
    url: ENC[AES256_GCM,data:rJLIJY3EBWPhsv/pM0QSQg0RYaBIgdFS41Ap,iv:LJcfpYBmpgZJyRysJp5BAVYZwdYF0GncirH37slFYuQ=,tag:H3ut9k4qlCiiMdOntnYGmw==,type:str]
    username: ENC[AES256_GCM,data:8ijp+t8=,iv:d5rAMnOLIj7f+lgsrc8DqTfU4wAHX5pbNqowm/mLxRM=,tag:idOYwLdY3Fx/oA5C//2+Nw==,type:str]
    password: ENC[AES256_GCM,data:yEzfyVou/XI6TlOhyYjq7M3hBmqygtBAdvffrsiy3zHAR7tj,iv:qIskwUJmBuxXwho8zDmi+gwBJB7tVXqwaWbsBtarI5A=,tag:gnQJ/IaBK1FFo0H/lgLiuA==,type:str]
prometheus_fly:
    url: ENC[AES256_GCM,data:LkrPmTmsOJO0IIFMawtszd33tubOjQ6VqTlh8Vo8sSfJKgj5N4Q=,iv:ESobkfE+skcKYLa31NTCN5muY1LCo6WYEoSfQnkW/A0=,tag:DGtNdqmoqEeTfOP5H/aU3Q==,type:str]
    token: ENC[AES256_GCM,data:PnxtIhigJYe7wU9iDVje8yfFufQM4xhHb0uARhH49YPnGDgyPhE5s0TPNRGmYs8=,iv:L8hCxuwbMRaZu3EA0vmjSOxev2BqeTrNWBAUgPWIMVY=,tag:zBH7EflpjymUnoe3THw/cQ==,type:str]
tempo:
    url: ENC[AES256_GCM,data:g42PPo7gIpZn/YUF63sUbGYWGrYA6qLDedvlk44htTmCCxkWggy6rm3dLg==,iv:2c7VC40oiYvHCrcFs6tkx8QDHtzGGJ5DN53JTwYAjjI=,tag:IDQ71GiQB0zKmVVdIIhvUA==,type:str]
    username: ENC[AES256_GCM,data:MNL0tg==,iv:TSfa8/GCuVUTfYNrNu1UzGGMIaERQTAubt+46dKW/Io=,tag:/JPZwM+vdPc+o4SIi2UazA==,type:str]
    password: ENC[AES256_GCM,data:Z2LHC09+UnhzBxphYdAcnt2Mc4mNWhdUh1xlAkoOeYM/ugY0zpWH2my4oHyRW5Jk6njuMNW5hURgsuHNgfWY1hskSgqYwXQhF1Md88yfHNiw6I8CxubmM4bP9bsW2Cdt+Sb8a9T4inx0Np7e/RUwHt+tRgbO1ltV6dH8ow==,iv:aDvNELy9m23iVdKOiD1Svz96VQLILJFv1NKofTU3sLc=,tag:OiZ9QcVD/sH1/gS9RNcJ/Q==,type:str]
loki:
    url: ENC[AES256_GCM,data:oVZXYdJzaNY9aYuz1LZWVhM6ivuvIOnAjASKQxkI91nkFBEBCioZMoc=,iv:YHVVkCAJvG1yRWruV2i3GZAV4QjJVSrELKJSHfS1EfI=,tag:XA6biFWlFvih9SUvSNugQQ==,type:str]
    username: ENC[AES256_GCM,data:pkLBLws=,iv:8tIk2iGqLTkwiCoBCg0aq0A6pBJ7QK8dDZakulS8WNo=,tag:4zBpC0aoVHi+78E+iHYoOQ==,type:str]
    password: ENC[AES256_GCM,data:jxkZ4fSjBYPfLAVr7PSHQkkTsFkPxPkHBh6/koLe/cdUK2i2pr5W8HXQro4tGthnR2lkwhWvSqVirtQrAz/wsKpQXCriRtaAf0dd2VuFJyforXlTMoDcKcnm4kDy6KlTMGhAUwXfexTZzR4e0j45/xxud3zpmB4WW1O68g==,iv:8XqnbLgRWiXuuDOhu79HANEmjoze7WvxSovb0TFDQ7c=,tag:0evWLOh9gCso/sJHewMMXQ==,type:str]
ldap:
    host: ENC[AES256_GCM,data:fKUGEdQuWRvYyA==,iv:2BQJbbUQ9aoZKnH8/KUotLkagIM4wpdZA5yFSFREKiM=,tag:l8rlnlnbvPIvnMxTZNcVag==,type:str]
    port: ENC[AES256_GCM,data:OLxw,iv:+JARDn2+vB8PrJZxCXV4VeMZqz6toLYsllSr6k4+skU=,tag:brDvmptvvqhv1Ut6hl3BTw==,type:str]
    bind_dn: ENC[AES256_GCM,data:S+BtHvKaRoXqNlX50I+YhTTW9pI=,iv:gylcbjwG1xP9ISm4esjNDCjTPBc/mtnpFwus8Nvepq4=,tag:UclnHhBzV52r/hyhTQ1FRw==,type:str]
    bind_password: ENC[AES256_GCM,data:puh1nX5C4DRJw3kZXgXLSVMPX+XCjoiGEIIczo41,iv:WUYM0IvOCYUbUNZybY9ulNZYEPbBLdSMeoOwWhTyGQs=,tag:n9K6yAjET09GmTszz6/7Kw==,type:str]
    search_filter: ENC[AES256_GCM,data:H70tMhhWWxo6,iv:eRvCN/POUe45AxTG58s/tR4ZGp7OeeTJDfmYFiCesyg=,tag:5jKb2XNsMBZKbscY/AMBfw==,type:str]
    search_base_dn: ENC[AES256_GCM,data:IP95H21+tFf9eUfkC1itkizrVmFz,iv:3PvWEqTqE/0kCaEx+v6rfc8HAeT1L1KE1EzDcDwRNgM=,tag:KCJjcwg72tUVTgdV+Eu3MQ==,type:str]
    group_search_filter: ENC[AES256_GCM,data:qvEG7CbqxRgloYK7/9ZHdqA=,iv:2d0dfz2C92Qo47Y2DO9nwguDY8u2OePdUWFlWUO/XNE=,tag:keVqnhXehDwumfQ31uR4FQ==,type:str]
    group_search_base_dns: ENC[AES256_GCM,data:MG1kLkokrJz/LsjkqhNYc9qODhBc,iv:nZYGz4NMc5Qn7LxyQS1ExKo2OgfhMS/kVBqLkpIfqdg=,tag:4KpWU+7xsU7U9z/p4TVwSQ==,type:str]
    admin_group_dn: ENC[AES256_GCM,data:uR9t4AVPHI24TUiw1ptAV2RAdz1E7ghGUTj6qXVNDeUE98e/Cjno,iv:vhhTIjGOvEcJLxXWIDl/AzK3Z5HSR3RS/3nVlZEl1ak=,tag:LgqdCjTjCXfx5jCTFzPxYA==,type:str]
    viewer_group_dn: ENC[AES256_GCM,data:oTm5nJ8tDQ34mGRfhk2dhpsHoWrZsPqMo1vSw2lj,iv:xQx3+w0Hbh/lMh/QnG7rO29uF/1i54mHcpgHjGONmI4=,tag:xIjqtMd/ATDw432D8gyZcA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ej7fjm78n44tz3jnr6hkzhraf97egzekjfy87rfmhlnv9flwy55se0c5gz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQUIxZFNjVXpkeC9mblhq
            ano2LzNHd1dRSS81S3c0eG5ZQmp1L3JnQ3pNClhsR3BWN1JES0h4SE5RV2t6WUJK
            Mi9JODVwMW9uQmVpN3JrMVdVOE9QbW8KLS0tIFNFaUVwSkI3RDVjd3ErQkJCMjNW
            bUw5UFBkRDh2dDVKcE0wb1VlbEdMaDQKri/LcPPhwu+bARxV8yI8bA+JvtcQtHPe
            1igtgmadTOONH3JYHQJnwGaqVOCUQa+o+0K02ipPJHELzlyo+l2SQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-06T16:15:00Z"
    mac: ENC[AES256_GCM,data:pcA6f8zFI33dmfideR0KJHciia6WSOdTXv3sNH3Zd5ehrpHA9pWbCpSrkkMATZ25cfnvA/Y+XE161a9dsuMlLq2LXEAawV6xtGPmZIIias/FRzE/ASPQG5m1uJ3ESgo/oZOeYBpeqgkjDw7NBT1R/7H1dRlydg1FebxQx6iPAFU=,iv:964CLpTEmZHOHBjvW8nDjNbE/nO4EaqBHvzok5IS5QA=,tag:ECeDLgw8s/I5LnBPqJNOeA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
