apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: opentelemetry
spec:
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.104.0
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s
      resource:
        attributes:
        - key: cluster
          value: "plum"
          action: upsert
      transform:
        error_mode: ignore
        trace_statements:
        - context: span
          statements:
          - set(status.code, Int(attributes["http.status_code"])) where resource.attributes["service.name"] == "contour"
    exporters:
      debug:
        verbosity: detailed
    service:
      pipelines:
        traces:
          receivers: [ otlp ]
          processors: [ memory_limiter, transform, resource, batch ]
          exporters: [ debug ]