{
 "title": "Envoy Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(envoy_cluster_upstream_rq_total,cluster)"
    }
   },
   {
    "name": "envoy_cluster_name",
    "query": {
     "query": "label_values(envoy_cluster_upstream_rq_total{cluster=\"$cluster\", envoy_cluster_name!~\"tanzu-system-ingress_envoy-admin_9001|extension_opentelemetry_otel-collector|projectcontour_envoy-admin_9001|raspberrypi_inlets-exit_6868\"},envoy_cluster_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Requests Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests count (2xx)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "60*sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"$envoy_cluster_name\", envoy_response_code=~\"2.*\", cluster=~\"$cluster\"}[1m])) by (envoy_cluster_name, envoy_response_code)",
     "legendFormat": "{{envoy_cluster_name}} / {{envoy_response_code}}"
    }
   ]
  },
  {
   "title": "Requests count (3xx)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "60*sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"$envoy_cluster_name\", envoy_response_code=~\"3.*\", cluster=~\"$cluster\"}[1m])) by (envoy_cluster_name, envoy_response_code)",
     "legendFormat": "{{envoy_cluster_name}} / {{envoy_response_code}}"
    }
   ]
  },
  {
   "title": "Requests count (4xx)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "60*sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"$envoy_cluster_name\", envoy_response_code=~\"4.*\", cluster=~\"$cluster\"}[1m])) by (envoy_cluster_name, envoy_response_code)",
     "legendFormat": "{{envoy_cluster_name}} / {{envoy_response_code}}"
    }
   ]
  },
  {
   "title": "Requests count (5xx)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "60*sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"$envoy_cluster_name\", envoy_response_code=~\"5.*\", cluster=~\"$cluster\"}[1m])) by (envoy_cluster_name, envoy_response_code)",
     "legendFormat": "{{envoy_cluster_name}} / {{envoy_response_code}}"
    }
   ]
  },
  { "title": "Response Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(rate(envoy_cluster_upstream_rq_time_sum{envoy_cluster_name=~\"$envoy_cluster_name\", cluster=~\"$cluster\"}[1m]) / rate(envoy_cluster_upstream_rq_time_count{envoy_cluster_name=~\"$envoy_cluster_name\", cluster=~\"$cluster\"}[1m])) by (envoy_cluster_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99 Percentile of Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, max(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"$envoy_cluster_name\", cluster=~\"$cluster\"}[1m])) by (envoy_cluster_name, le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}