applicationName: httpbin
deployment:
  image:
    repository: kennethreitz/httpbin
    tag: latest
    pullPolicy: Always
  ports:
  - name: http
    containerPort: 80
    protocol: TCP
  resources:
    limits:
      cpu:
      memory: 128Mi
    requests:
      cpu:
      memory: 128Mi
  containerSecurityContext:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
service:
  ports: [ { "name": "http","port": 80,"protocol": "TCP","targetPort": 80 } ]
ingress:
  enabled: false
  annotations:
    projectcontour.io/tls-cert-namespace: projectcontour
  hosts:
  - host: httpbin.lan.ik.am
    paths:
    - path: /
      pathType: Prefix
  tls:
  - hosts:
    - httpbin.lan.ik.am
    secretName: default-tls
extraObjects:
- apiVersion: projectcontour.io/v1
  kind: HTTPProxy
  metadata:
    name: httpbin
    namespace: default
    labels:
      app.kubernetes.io/part-of: httpbin
  spec:
    virtualhost:
      fqdn: httpbin.lan.ik.am
      tls:
        secretName: projectcontour/default-tls
      authorization:
        extensionRef:
          name: envoy-external-authz
          namespace: projectcontour
    routes:
    - conditions:
      - prefix: /
      services:
      - name: httpbin
        port: 80