minecraftServer:
  eula: "TRUE"
  version: "1.21.4"
  difficulty: easy
  gameMode: creative
  overrideServerProperties: true
  serviceType: LoadBalancer
  externalTrafficPolicy: Local
  memory: 3584M
  rcon:
    enabled: true
  vanillaTweaksShareCodes:
  - VBeQiV
resources:
  requests:
    memory: 4Gi
persistence:
  storageClass: nfs
  dataDir:
    enabled: true
    Size: 8Gi
serviceAnnotations:
  oci-network-load-balancer.oraclecloud.com/is-preserve-source: "true"
  oci-network-load-balancer.oraclecloud.com/security-list-management-mode: All
  oci.oraclecloud.com/load-balancer-type: nlb
podAnnotations:
  instrumentation.opentelemetry.io/inject-java: opentelemetry/default