apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: demo-blog-ik-am
  namespace: demo
spec:
  virtualhost:
    fqdn: demo-blog.ik.am
    tls:
      secretName: projectcontour/default-tls-ik-am
  routes:
  - services:
    - name: demo-blog
      port: 80