#@ load("@ytt:data", "data")
apiVersion: v1
kind: Service
metadata:
  name: demo-blog
  namespace: demo
  annotations:
    kapp.k14s.io/change-group: workload
  labels:
    app: demo-blog
    app.kubernetes.io/part-of: demo-blog
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo-blog
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-blog
  namespace: blog
  annotations:
    kapp.k14s.io/change-group: workload
  labels:
    app: demo-blog
    app.kubernetes.io/part-of: demo-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-blog
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
        github.com/revision: #@ data.values.git_revision
      labels:
        app: demo-blog
        app.kubernetes.io/part-of: demo-blog
    spec:
      containers:
      - env:
        - name: management.otlp.logging.endpoint
          value: http://otel-collector.opentelemetry.svc.cluster.local:4318/v1/logs
        - name: management.otlp.tracing.endpoint
          value: http://otel-collector.opentelemetry.svc.cluster.local:4318/v1/traces
        - name: management.opentelemetry.resource-attributes.k8s.pod.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: management.opentelemetry.resource-attributes.k8s.namespace.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: management.opentelemetry.resource-attributes.k8s.node.name
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: management.opentelemetry.resource-attributes.host.ip
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: logging.structured.format.console
          value: ecs
        - name: info.env.hostname
          value: ${HOSTNAME:}
        image: #@ data.values.image
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /livez
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
            scheme: HTTP
        startupProbe:
          httpGet:
            path: /readyz
            port: 8080
            scheme: HTTP
          failureThreshold: 20
          periodSeconds: 5
        name: workload
        ports:
        - containerPort: 8080
          name: user-port
          protocol: TCP
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1002
          seccompProfile:
            type: RuntimeDefault
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: demo-blog
              topologyKey: kubernetes.io/hostname
            weight: 1