#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.subset({"kind":"Deployment"}}), expects="1+"
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by=overlay.all, expects="1+"
      - resources:
          #@overlay/match missing_ok=True
          #@overlay/remove
          limits:
          #@overlay/match missing_ok=True
          #@overlay/remove
          requests: