generateIngressCertificates: false
rootNamespace: cf
adminUserName: cf-admin
api:
  apiServer:
    url: api.cf.ik.am
defaultAppDomainName: apps.cf.ik.am
containerRepositoryPrefix: harbor.ik.am/korifi/
kpackImageBuilder:
  builderRepository: harbor.ik.am/korifi/kpack-builder
networking:
  gatewayClass: contour
systemImagePullSecrets:
- image-registry-credentials