#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.subset({"kind": "Service", "metadata": {"name": "openldap-stack-ha"}})
---
spec:
  #@overlay/match missing_ok=True
  externalTrafficPolicy: Local