prometheus:
    url: ENC[AES256_GCM,data:ZMjNaPon7IKaPHWdDb4Yj6KWFi2TbPzw5PpT,iv:Bdho7ykQoqr2lvlBbXR1HVq6CgmRu8VHidfPh9CCe1Q=,tag:Y50T90Q+yPFTfqFU3DMyyA==,type:str]
    username: ENC[AES256_GCM,data:nDozw9k=,iv:egQCVleKl42ajNL+WHAIEEa3s1w87Ud8LZh6jvsj+KU=,tag:lAO+FdHxxlQ5G84UcYfMVw==,type:str]
    password: ENC[AES256_GCM,data:nphQ+AwkYWDc0rGqX+ylR9WtO1I8m9R+V4qSdDSnofRzBzpt,iv:iRs24l6Y0LRdCgnMd0FcNIz4VH0OjcSGSPpqobR4pHU=,tag:aF2gazywSjUhFvD7thAYhA==,type:str]
prometheus_fly:
    url: ENC[AES256_GCM,data:YMpRfIbUWaK2oJcp47CM5BUEKj9NOarkCOw8G4NkL7s3WT8PvmM=,iv:2gngJD3bpzYN+ztGDq3N8pSuwBiPvKHxYAgBDWmfmcw=,tag:FEh8gBekHPC253tWQV5GUg==,type:str]
    token: ENC[AES256_GCM,data:WNzAVW/6GzTWj8KTAhyAIv6CmDFr+N3600Jpvh67CCjn+AJcwa1IYywG+T7aCag=,iv:83h/fkpCLaslxGJpXdgaG5TnjyjsSGsAQq+ePNDdum4=,tag:NYD7UGrBkY4d74w0r3cfXw==,type:str]
tempo:
    url: ENC[AES256_GCM,data:wnLkxPqieRyf1OtAT2KCfrO9g64cQBepj3CNxBDlqiOoltNNa2cVW3HtMw==,iv:ibWDLWXLb5I8b8hyVAwjN72paNfrtcZPsiFO+7Fa9nE=,tag:WCmc6dMdzeu+JhYcJtfOUw==,type:str]
    username: ENC[AES256_GCM,data:ZtmyrA==,iv:tPj6KNh7TAp2qoI8KjN1OIfRPjE2YOL9fxoVvPruJG4=,tag:Wlu4a6roNE/cDFUKpjT2EA==,type:str]
    password: ENC[AES256_GCM,data:clHplBkGHR7ol4dD3PtizXcbOLCVPzc6ANH+XGUxHg5JB/CuJI1JSnDpTGA70CrTl2mn/LOMlLL8vTOyhHc+x4xTmrxbvywy+VzFLKzjwAL+qDW6fppOaOsK5sqnUH1rWMAy/LXVOIPUWzuXrwoS6CGDMDbVoNsImQfnPg==,iv:1Oe1jCM1DrVNzjHl1YYjFmVmVE8rK4KbD/Y2xthTIPA=,tag:u6OT4b5H37BeYLGP07AhvA==,type:str]
loki:
    url: ENC[AES256_GCM,data:GtuhPCdXKLlfkQXDYHImWFN5SaihhYGZkIcwHGmvx9qinqOowuYWI/c=,iv:iD0D+AMRduDw1hUTvMJXOEAyzdOc4iaGXS2Kpre0JT0=,tag:R95feOXYyIfeYpN6F3X6RQ==,type:str]
    username: ENC[AES256_GCM,data:rfQ1dNg=,iv:D74EzsrOxgWBnTsi1YRzTMUt+p47lWpwGxhu3/95eNg=,tag:ibUfj/2nQxzUkghDTUEerw==,type:str]
    password: ENC[AES256_GCM,data:0HfRQUIY+mxMcQJeKDidR7JqHSyxdLgSFcoSUZaBz7MKQOlLM54qVYB2DKqHdWTyWPRJ/NLSjZ3etCFCknnNgv8dNRzeFSMm0gUjnWG2712n9ItX3jA6Mej+abZ+hXgvBoA1ewypyeTsXNbWOtX9QtBjbC1hHuqD8g1C6Q==,iv:mdRMRGtVPSM7H6TRLgvC7Np/rBQZd3m5JF33P1XJg2A=,tag:KLVihPuJunhVIxcegPXx8A==,type:str]
ldap:
    host: ENC[AES256_GCM,data:jMvKg2x04ZiIdg==,iv:wPhboUEKFR38lJqioPkoGO2Zq20AWpoUVnDBWY8DZOQ=,tag:DWzPbzEnyCJsgmIPqa11bQ==,type:str]
    port: ENC[AES256_GCM,data:yuGK,iv:cC8dYZucWj1MPQofeOlxupXVLNvmlvORKxVaH20+RUY=,tag:rGzW2JkIEA9mfqkoV5nTOQ==,type:str]
    bind_dn: ENC[AES256_GCM,data:Sss91dw+QzgzbA7niVOlpo8fk3s=,iv:S8nPpdirVQ3ST3ybjceU06A57ye/cNkPYXygif3002k=,tag:Q2xWOnxjQVaNpqqNbnSvmw==,type:str]
    bind_password: ENC[AES256_GCM,data:gGJL/E4vkYhYoIyaP2gi53AEiPZqmuM/E4gsllhG,iv:gRiCQWCx25cjpMLtklmZhbzgc7H2CH1eTf73RETwNZM=,tag:C9N1JVu1TTsT0nIsDqwIQQ==,type:str]
    search_filter: ENC[AES256_GCM,data:6zTvIBd3BWRoqaTTo2VOZtkfS6E=,iv:Od5HxGCOS/UV8efntD9LYNXmoeh353W+YxYNroctxns=,tag:e/Y6OW6H7RxGBgP/D43JZQ==,type:str]
    search_base_dn: ENC[AES256_GCM,data:Ir/78D0lr6P8dL6cnnDg9DgL7TwV,iv:Jr+Qao0Hb2eop85js9oxanx8klVGO2oEbDmq4FHGKdk=,tag:t3A5+Wy4Tblr8+QLxGk7jQ==,type:str]
    group_search_filter: ENC[AES256_GCM,data:8KsuP6HdLEiNwupgTrIVasg=,iv:CRE0esiqvRFyO3t1+ZN2hn2SzCGBitZWVXXrWjNPfVM=,tag:bI5QoyUeAMP5+JbVvcPmkw==,type:str]
    group_search_base_dns: ENC[AES256_GCM,data:bk6ChxdAxaRzYSZKiZRj9hg2vocQ,iv:gYmtxmdY1AjQaacb3okfVj+jxh0GuRRwaK6gfGWWuMM=,tag:cko5ljMwHebCsKA5NUA3Sg==,type:str]
    admin_group_dn: ENC[AES256_GCM,data:fqGjMdP5Hmf3D/DI0jPAXiOJwHiZYrpst+T5FvdPxDCl7iDSofwq,iv:Tvz2VfhT/6/K4PuFbUQj6/0s2b2tyuSeT4vr8WiUAHs=,tag:xGft3azx4kUXAJjUnlaxrA==,type:str]
    viewer_group_dn: ENC[AES256_GCM,data:O8vu/lB22Jr3JmIq9s8FH9QE1AY6JmHdKdDw8XP0,iv:nZXDrb0+teDEjJYkauYNoYE/Qbbl0sjTg0eI90aQNAs=,tag:b6rOIKh/Ky5kSMLSPvGJnA==,type:str]
oidc:
    client_id: ENC[AES256_GCM,data:y4ywrpj4NVMo2Z18hQGmqeW+/Oc10PIiNJ0/uRbgc8h3kLz5,iv:Erxh5k66LIgdDRLkpLyJvL3BcyHGpDUPEp/Y4Z3wmsQ=,tag:T8L7ZAT5hXNbkwG5peywrQ==,type:str]
    client_secret: ENC[AES256_GCM,data:oSjAafrz5X7asL+gG6Zd7lIcaqkytbRnCLt8ndOvvw35knuL,iv:Wp9OatdTTA+jX7EJ+HiSk4CrNY8nc5699xdUdsWtvk8=,tag:QzqcJmDgEH5r3b7xKg1/9w==,type:str]
    auth_url: ENC[AES256_GCM,data:tlEvY3EaAm5bB/Ck4V2/PpDQMs13wfHljTqpR/Borgd6VQ==,iv:I1J6EUIKKVghlicn7ILPbbq6yCyWAdr00ErbilZTRKM=,tag:TXBWK7/Oih1qvqqNZSXNbg==,type:str]
    token_url: ENC[AES256_GCM,data:2KqkqL/kT5x7J9SC7c11I4qCUDEJfKkP7SGjjQI=,iv:074OoGra8lnHHbokxXdRUNb5mf01lwyvWXTDN8XTHY8=,tag:EBG1LG9zNYm96UDCigLqaA==,type:str]
    api_url: ENC[AES256_GCM,data:IAjLJ5Jaa7AMBy8CP5Jmit3twwu0MHkQTpc=,iv:ThFIUBF8wS45PTK4moMDDjuUmMCoz/unuz0FBqIMP2o=,tag:OhP/vIy/2ttyOK9oUpBY1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ej7fjm78n44tz3jnr6hkzhraf97egzekjfy87rfmhlnv9flwy55se0c5gz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcFJmZUoyRHNWbTVXc2px
            VCs3bEw2SzZaUFIvdTVScExUL2Roby83aGdNCmEvckQ5dWFYbTdINUIrTlZ6K0wr
            cU5hWi9Eejk4TVU3V3JaQktTMWludDAKLS0tIHlKaHU2YkwrMlp6Q1dFeTNtdWUz
            dVBDYWZmL0htZTJON2ZVd3FQVWRtNFEKEll84sf4nA9aXpfeNPMUuRSwbuXZG7YV
            jCu6Rh6r9b4eB8R7C4s3x2/JR4tDbo9mWU6moKUMjTGNUBdf8+bpJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T13:57:37Z"
    mac: ENC[AES256_GCM,data:YZMlHHV8qnEYJ6/4a5lCjCt4vJ8L2Ra3QIszLNhqXJXkQI7AftENBOudkQ/30EGH3s3nLirm8dGAJ7S4dXYc0TPXUP+IHqhYu1wfknGJ96ProYazEop+U9uIiX+s4UlfPluHbqJ4Iij9mKj5rGpQK32jPogth5p0/0qbKozLqdo=,iv:pEkj+13ZtH97kl3wxFIhoJ5rnUa8IdqD3E/d86vppYk=,tag:K8nSMN0X9IaBiiZ279zDKA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
