prometheus:
    url: ENC[AES256_GCM,data:gTQfp6BdMQ6R6+l3io7W3dMPJ6I9KceK6zjO,iv:0R3K8KH3w5plP5yoHUJbg3k8kNm/8UbCIVNqTDu1wxU=,tag:ZV6WGvz895GJ1ijmRvYnvw==,type:str]
    username: ENC[AES256_GCM,data:RdBTZ/g=,iv:PmSDUByQbKsRNHWsYCW2NOHvgJYQYvdP0KLAxxdES1g=,tag:mou2yep7p6+uDbv8fBfHRg==,type:str]
    password: ENC[AES256_GCM,data:e5NwS7iy+dS+V168jMNPd2mbb4Z+fC8H9FUSVMD+9rNRsMEh,iv:5KWxUBk4DFY6Zdt+kPfOyPxECxyR3YhwHOGKgXN9GLM=,tag:RXdDEAV6B437rJOCDIbqQQ==,type:str]
prometheus_fly:
    url: ENC[AES256_GCM,data:TvNuryLS98Eld66Xp9PxnM4P7pRZvHpS5R26nOrz6AzgQYdiqgg=,iv:lrTXOFWZZdhfbU4F2khBPOQ8tThU1T9eo3ukQ6akHO0=,tag:gL+99dCovSh6r1CWpz0G2g==,type:str]
    token: ENC[AES256_GCM,data:IEvWznL7oZA/GFkcT9Rrepueo9Sy5r9TsrHrDPSopQOAXZfrdMzi9V0Tqac4dbU=,iv:xI0MjpyqddkUHr5D22LpZnNowUzllQKNQaQLx2T7eA8=,tag:EcUezp0q4ZdlEsIv3uRE/g==,type:str]
tempo:
    url: ENC[AES256_GCM,data:HZ7Brp0BEjb6GSR4Ue5XGeXy36ltwxYFtnDjxwni/xuLBxvg7XGPbTut6Q==,iv:79mN4cJ7KmF8oacNbSHXbuGzZ65F3OHSoiii6SMuin0=,tag:bScu1TqCCl6qQMiMHj7+RA==,type:str]
    username: ENC[AES256_GCM,data:gTZb+A==,iv:+QWNWvpqUru5UMl0k5av10myxq6ch5Itu8GKxtlezOQ=,tag:fUo2+t/PrLIWc7uLpBIF0w==,type:str]
    password: ENC[AES256_GCM,data:HaOmRMrn5AvEqtjTxu3tlrA5mwqjP3N0S+/o6axQwDEOaYR3NolZDrNaQQV3tlFgg4vjCG6YO5m8DXaJ3gN02iDgz9GjTglpyS6PQ+eNrgfnTGv7H38rAtO2GSXY6yBto19CqjnAKatylU9Z4WwpT5yfzObC/qIF7TZnhg==,iv:4JtsoPkkkQQkUY98xBTHftFei+oW0x3zd/A8RYo9Dvg=,tag:IyfCwiMmeP65Jym64TcB5w==,type:str]
loki:
    url: ENC[AES256_GCM,data:gufT0ilUjmBPqCKN+/qw/PLU/BCfs66LpyU4rVa8xL7h5x7O8sYVwPM=,iv:0e0u2Q7xNdVOyIdPw1RfzerzrH8TPOvHKC36adc/GjA=,tag:Xwpx15PgEgh5/FLBpSKRhg==,type:str]
    username: ENC[AES256_GCM,data:/2zx8lU=,iv:738MsT1OiLrR1/eVpVycxPUKKrKNkjCKZ/1wtTDBQ74=,tag:O/0qiJCfO5LGUoTmmlBN0Q==,type:str]
    password: ENC[AES256_GCM,data:wimEDKWh5BHm7/M1AXN16ON9gdCUuiYv9CQCC5Ly+fEuz2VCzxReByRX2WVfUFN1TxB/o9lOdyt1TPH1Z+uXR8mYsBPqzKkrAnOAzCMNmp3ncAHtpAjr2+Af6UzjRY6a/Bx7gdwsw9uEofyAENK+UvQLCWWvtKe4ikL5Ew==,iv:krn8QIvQaV+0c077z/5b1iYqn3B5ZCNmMJligOn0ssQ=,tag:wzOt4bIpWEr5/bHC6NNiLA==,type:str]
ldap:
    host: ENC[AES256_GCM,data:TXI+yEz6bnqSIA==,iv:IsCBZvFooPaL8nstKwnYtdghQ2OhdO1wIC7HWfZNiP8=,tag:fSXa5EJKtIKXZoFTUR06kA==,type:str]
    port: ENC[AES256_GCM,data:x9F8,iv:xyo2MbQKChHPXfSdRlWSuqTNMa+gexeuTEPJHd87MFY=,tag:52HvzerQbNGhGye/V0YoZg==,type:str]
    bind_dn: ENC[AES256_GCM,data:xzxzFakDfeNj3xPlzA2fb/w8RjQ=,iv:8HCsjOSIaRp9v52KlUHcomS8Mt3OGunU+d532BJinbY=,tag:EC4T8kpt61nSNL6U0Ts0bg==,type:str]
    bind_password: ENC[AES256_GCM,data:IcaW4YV3fJsDkslHHHFcDvFZ6/fM4KcVNZzVlpQx,iv:9bzoQex0F6nja42V3MxqS97jdVAwnGrvKlz4CUzjgd0=,tag:ZrWWIABpm6GhFgcTq2i7Vw==,type:str]
    search_filter: ENC[AES256_GCM,data:9aqnl323ROqve3FqqOKZ4CV6XAU=,iv:gYsgL+58Lb6JQqp0TYkzUJYWa1onOyQo25L5ADa1RiU=,tag:gDmDHyGh9GcJUeW5dw1tGg==,type:str]
    search_base_dn: ENC[AES256_GCM,data:pKOp2ajNGeyt490HIDGBN8Amk0/r,iv:pKIvrbOO9ZMg1IZMxuDYDoXdBEaIJFNk4AqU+fWu7Co=,tag:7mdpjT28nVYf14enw6itIA==,type:str]
    group_search_filter: ENC[AES256_GCM,data:Ud/NTGW9SVj0ZKkLuo537DY=,iv:VoAoLfQHPjiMKynGuElwIfo/KAbtRGfe1Lo46nMeGws=,tag:wbp/Ip8dM0e9eb0i6hNTeg==,type:str]
    group_search_base_dns: ENC[AES256_GCM,data:xHHN0611kIICR0dvtKWDnfHXt7/s,iv:REqGKg8uxrr8Lt9bi/j/Lo6PTQI0CjWa5LadH5FEFWQ=,tag:2TE1k5smI0tzppwHxumTcw==,type:str]
    admin_group_dn: ENC[AES256_GCM,data:VaYYZUMNRuNrkT/ahefyIjKpPLUSSis0OLajFQ80K0ek2kCQB8nN,iv:O8lWaHi7FHvZzXvTNXyTOaL8G2Q5GhJhnIBOkNooul8=,tag:khaqbHH/iC14OaNh0ZZnhA==,type:str]
    viewer_group_dn: ENC[AES256_GCM,data:Bew1lCiilAOelhcofZVuLZN+cRq5Z+SR4+dMo6+k,iv:2rv1ozx95GPcxZq5/QTDg5g/2CbQVTBm4ls1JV2Lh3k=,tag:ol72CHeasGxyuzP6eo4O4A==,type:str]
oidc:
    client_id: ENC[AES256_GCM,data:Fe5DV//rWo3viggdaxCztQo81U9BcxAdQ9Snn6mL/eF4J/ct,iv:3GMydo93i1ITYd5jyzy+B2P91fqpbtFVcRYong3CD1A=,tag:2Uw4JUCoHI6s/N4RLUzKTw==,type:str]
    client_secret: ENC[AES256_GCM,data:jIH24ItLQrsbqN3e7fNuERtuhEHZ0ba/aaT1jiJULNroQZKo,iv:igaxHUDpShPpQtA9yJonqTuXtdrj5rFLEEg5oGNI2ek=,tag:FFo/XB3k35UB8RptZC+FZA==,type:str]
    auth_url: ENC[AES256_GCM,data:Su5GGpEznZe9Lf1Pxyml7Eq0ts5xyYr4Trnphd/MPv7U,iv:oPm4li97oox7XUri89NfPezTMhzNYTCEn+mA31/RGe4=,tag:lqZy6uI/Qm3+Ueal1W/SRA==,type:str]
    token_url: ENC[AES256_GCM,data:DxJBoMbAi6bfFlHUgRO5e1SqgogWNxAd9PqOUE0=,iv:R0JguyNi60L/Y084WwfgyLh+iJEg/4+TZmbn4H3UbPs=,tag:TtaKMd8Q+DU86suWP2JXMw==,type:str]
    api_url: ENC[AES256_GCM,data:KbcrIdioh45GkQd6KT5ol8Geh9Y0BmHbqw==,iv:UPDRJdPi6L+u31BFsyEEtzK61v76VFbH+DjlPeXIHs4=,tag:qpkkxSTSoUsJN1ZsNzOtgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ej7fjm78n44tz3jnr6hkzhraf97egzekjfy87rfmhlnv9flwy55se0c5gz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQkhsL3JRTjUySG5vYkZw
            bGdxQzg0d2thWUYxaG1FaGFtakZTSHhqMkVvCitXbVE3amhYb2FOY0czTUMzRXhC
            NzJHbFV0UG1DeEpFYjZjNWFpdzZHSlkKLS0tIEYwNkNlSFpDQ1ZMejRjWDlqK0t1
            U2NablBzZURNU3pBT0x3KzNINWhIR0kKQn3IMXaydTu6luqeXStKnzQfRC0+E6FF
            T7xofHhJrOp7GZKdQIcBR2rAIoedIbA5slrKNuq/nyY+KqFGWoMj8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T13:59:51Z"
    mac: ENC[AES256_GCM,data:gSiN4yagDeCUMe2SfOwzD1SgAW0UoxemKGEsOa5YTQUvc3fKyIuitZG2wrBksC4BJvRkHP/Mp197kpYN0uSYN8o/81ynPMKVY30dw7C2BFdc351Rcuc2cnv1ErOzScl5DpIM3tynYK1LsE3DdYCQqu9PaLxikJAknuRJB+vNQEc=,iv:rjGRQsoiqz8lA65KXwtvq7OsqMH/z5KdqacTpNzdcl8=,tag:9IVr5tiIedJbuu2xVralUQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
