prometheus:
    url: ENC[AES256_GCM,data:EdGc93DrrCFIXb+0o0ssLeTokSlwKvgaJ/+K,iv:AHRfCLzePH1x9uQF0IVwltAF6ZGSVP/CAyUv6LNR1Lc=,tag:fplCiXr6PtfrQ4+3Q8H5BA==,type:str]
    username: ENC[AES256_GCM,data:feK8fJ8=,iv:LPdd1AK47AHGXB8HqByBGEvsuxwcIXgo3UdMn4JFwkw=,tag:nOTwpdejjxv+7WiS7VEN7g==,type:str]
    password: ENC[AES256_GCM,data:vCFi35E8+UuCx+3xVXmapKNgoldKNLuzpud//kqNG50hSooS,iv:vc6mwsFQPzs4q6+zKJ6DiYXqXid7jKUkUagFkqjMCMU=,tag:/v0BOVA6RKzLtHmRJG/X7A==,type:str]
prometheus_fly:
    url: ENC[AES256_GCM,data:Ped5tCONVC/qWu/+VVkCi/jzFUmDbt1j/uM3xP5ZmN1A0CBSg38=,iv:qIoIaMTmfBiewKyEgqldJ96qpUYumuqZRNxfO9ciX38=,tag:k054FUkyRQXq8yDvQtZcng==,type:str]
    token: ENC[AES256_GCM,data:b1K1+GJdT1VN01y1nWp8EoOAbbeEiyO2ejZmf+pceyNMmj5Fxt/c63/AxqSo93Y=,iv:d4hZ22vDS652fup/mitca+akX+KUjFf3Sd7EbMCWruk=,tag:H0Ma5zoLiWYSHbcw9QrWIQ==,type:str]
tempo:
    url: ENC[AES256_GCM,data:cGL5ZgDtlEAjTKO4a3woi1mYyPEFcMoD9Dx1RtgBxuno5kzEjA2sKxzWaA==,iv:uYROX8IxLxcwAcT5h3AN7mryYvZOG+Iez4k9Sk2MOGo=,tag:QIcVEu1OamvV1p7fQ0F0Cw==,type:str]
    username: ENC[AES256_GCM,data:V9jiKg==,iv:SCKQJvc+ovK6yCjoSRPhxD7pYfStboP6BMb9xAf0GUA=,tag:lMUjwKVoosLBeuVYL4KMHg==,type:str]
    password: ENC[AES256_GCM,data:QbM6QSevgOql1d+4WTVa2NltuDsIjdvhHupllMkXe0Y2AifU973KVk3mkDzXzDRhZHIYX23+A5CmqiP/ywQX/JAFDaaU7z2Ef/zr/G5KqNN7kA2FaPOX1Fq7UUK2QPPzcEKqM44+iIKrWwlpydREux1oSBHDcUfzsqnWEA==,iv:qemv5rHt4QouiT3yNiB0NvRpl1SLTnE7WFqlI2JtpPY=,tag:IEM4wQpuI1Bx4mahPmI+Hg==,type:str]
loki:
    url: ENC[AES256_GCM,data:QrNaZHxYs0qdoEiFdmbRfp6B5ZoZGrBChx3buzp3QRP0/2G+23Bvxvc=,iv:doWwu9SfItUWVilm0QFCUPIIaanHeiT72U7DFFyd+gc=,tag:wfcJnqV+OaYEK4y2uecHVA==,type:str]
    username: ENC[AES256_GCM,data:Acpe6Dg=,iv:PS3JgZOwsF5bpa9k0l1NHaH1hlB93uJ86zFGMJATc0M=,tag:rGtFsNdAmLbEveeIkDgO2w==,type:str]
    password: ENC[AES256_GCM,data:oOWha6C2Cjm/Eq299G9X1O7uhh//IMMDUdKdsULkGRVSLzL56mYO1N4OU+iICk8GgaHBm7uV8LSczbauoDnhdA25hJXKyKbqsywCHAJcPfu4cu3sLDF8JSQJEnDtfvo7Ve72bj38tmFh6rYmwrGpcy01bP8MoOzEZ8CVgQ==,iv:bMZyVAiAb4ucaCEG1SbbHhwS8y4huVe2Gtbv0y+SfCA=,tag:TwUfzaciuj4hkX48C7Uw/g==,type:str]
ldap:
    host: ENC[AES256_GCM,data:S3j8aBYOeVF8rg==,iv:5b60NqsxlcjK4SinwdOdTpSad4ezksC9Na85zb93qkg=,tag:L5lq9f7P4SB+09bW11a3MQ==,type:str]
    port: ENC[AES256_GCM,data:KfWj,iv:XBOqj5Oz7XA5AbtMFeSsIJOuhCMQZEt88yhoL+0cFsA=,tag:EgLvWI5lnGhZA2lBYtvchg==,type:str]
    bind_dn: ENC[AES256_GCM,data:dcBiawITLyU6m9KIEuRaQxz5Seo=,iv:VRi5J8wwkeUVPR2cuAipa99g2AuEzuWxojQEZFzR0fQ=,tag:l4ERCw5EJk5TKRau5mRLZg==,type:str]
    bind_password: ENC[AES256_GCM,data:rBtDIimCTQQPnMGsqWjRd3X3FqvWj6yueDSts1Vq,iv:+Wk5HHVpXZn91H1DW+EYKaEtoGpvk3SJZbPb/yBRxvQ=,tag:+Wu49WioRG6NOEvq1DtWcw==,type:str]
    search_filter: ENC[AES256_GCM,data:F32UHeNKXrc9n4mTAOYB159uktY=,iv:yyfUmOjrL/KY+ABdK752z73hM44fotpA9Loy6xfqt5w=,tag:fU8Pqo86PnTHRvnfDLABJQ==,type:str]
    search_base_dn: ENC[AES256_GCM,data:/HkNKemDj674gcGBUXM2OK40QiH5,iv:YaeVzJQKi93cFlrufgzbvYzktVFnhnbx6iMv8E2ezNg=,tag:SNCyCSlDfBULtBzv9hLaTA==,type:str]
    group_search_filter: ENC[AES256_GCM,data:kWYR4bDZu+ZhKH/yFGqKRDI=,iv:p4yP9wYCF0ZR1ftw94SKPOqJIGjLn/jSPF1Ka2j6ZgM=,tag:Hic3m+VhdgxCQ8At1eJcQA==,type:str]
    group_search_base_dns: ENC[AES256_GCM,data:aXjdsXoxvokEMuPNrRcprB3V5HsV,iv:HVPH1OcK7gRuxn1kiY6AqZrYNBuqc7dyTa8ZCt6KVeg=,tag:tWuVewMR5V1W/bhcMqgTCQ==,type:str]
    admin_group_dn: ENC[AES256_GCM,data:rFOnIkB+Om1oyVM1oz/BmC8Yy3QUV5tNZbIT/vc9/aym7FWiRqEZ,iv:Kqe+scm7u5wagIKV8y8L/OOH1CUPaorSDppcSYKK2Hc=,tag:SAs454caAauPQxk8604U5g==,type:str]
    viewer_group_dn: ENC[AES256_GCM,data:csobtbNQze8ERgYJ30rmQ63pY9SxwQngJiyoBGOW,iv:hpUADHxrPmXZct3VO7NWPpyInxh2b3VGsnIqPeP+JOs=,tag:W0xULO6bKbZ8T9a1Uo0OMg==,type:str]
oidc:
    client_id: ENC[AES256_GCM,data:rIKJNMj3T6SlIE33hrul6MfhI886COxYMsNM5IOBuEWg6qXA,iv:K0d1yid9ww0GNfX90qm4kzYjolR0r9U+gjJ1lwMH4ZU=,tag:j+1bx6eKiICjQEwMMG+ZFQ==,type:str]
    client_secret: ENC[AES256_GCM,data:b6e19AyJgbanw27cpb2QxAHuquT8wDej/5yeMjiWr19Mb4oP,iv:hEkomakXa5xS01BWCQm5c44N3B9tIGRv0Lm+iYIiF08=,tag:rx/Q/zSEIjI1g5Yozl6hXA==,type:str]
    auth_url: ENC[AES256_GCM,data:it3eX+L5AsWTImzfFNmIsjpW/9jCCQEgEvyT/WrukEQf,iv:ID/Kio/61qHLiUlNeKWZfg4/1LpikHNkuZiWJ6CY7Yk=,tag:VVheErzpYuMdDGzcsymJZw==,type:str]
    token_url: ENC[AES256_GCM,data:HfR+MNDpyzMXsOQG2OvUdgPX6rv20nIiHKUrLXc=,iv:bj0pF6jReDee4qTlHAcwX5OtAnYiOzdzVuQz/7rFUB0=,tag:6DXIfyI4HOOdtw6s4JD1vQ==,type:str]
    api_url: ENC[AES256_GCM,data:UHP9iqrhKlaHtYAB6kD4xV5AMsB2kdswGQ==,iv:JbUCu6/klziWKL/JMBRdHjvQvJxJm67wB1DU53hM2LM=,tag:TjKyEAVXFztnJLHYrcQ2Yw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ej7fjm78n44tz3jnr6hkzhraf97egzekjfy87rfmhlnv9flwy55se0c5gz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUGdtOUZ5TVhtWDNnWS8x
            YWYrSHhEaEV0TnlCT2xkOUZiRXpXWmdrem1zCkxyQlgxeHBGd3ZYenpXeEVZTGN4
            TjNybG9IMjQ5eDFSVUdIT1RiOHVUYlkKLS0tIFRLVVVnR1oyS3Zrd1dKbkJhZE9T
            OS9DbEtsM2tQNmNuOGpFTUhmc0VEUmcK/c5XEmwtdxZMsUBQ5oG4NzZRTdv/WSRg
            rVF/rOr3PpJZnK7k1RAbq3+s3Q+9bV1z1yHuOIJ9tTw7gcxaaQHDhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T14:12:39Z"
    mac: ENC[AES256_GCM,data:Qe4ipjR3Wnd+d7z0C2KO05x2wPMKB+tcuChsrIRiG0W4bZhuWI/vQAZSzghIBJGPhNanuLSD4PmgVlUmERFYtiUUVIPhJT3ywhY306IMUbcvlWI8+ZBcPsjFO//qaboKcY5iwYdMGvAzqHQuKvoGNP5k5pksQMa+tLCf++jhB5w=,iv:CoRy/naj6T2Xq57xf1MN024Nnup0bnsTr02nGbRw6uQ=,tag:dNgiGCFHX7YpHBVunCZJUg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
