apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: rcon-web-admin
  namespace: app-install
  annotations:
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order.1: "upsert after upserting minecraft"
    kapp.k14s.io/change-rule.delete-order.1: "delete before deleting minecraft"
spec:
  serviceAccountName: kapp
  fetch:
  - helmChart:
      name: rcon-web-admin
      version: 1.1.0
      repository:
        url: https://itzg.github.io/minecraft-server-charts
  - git:
      url: https://github.com/making/k8s-gitops.git
      ref: origin/main
      subPath: lemon/app/rcon-web-admin
  syncPeriod: 24h
  template:
  - sops:
      age:
        privateKeysSecretRef:
          name: age-key
  - helmTemplate:
      name: rcon-web-admin
      namespace: minecraft
      path: "0"
      valuesFrom:
      - path: 1/helm-values.yaml
      - path: 1/credentials.yaml
  - ytt:
      paths:
      - '-'
      - 1/config
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true
      delete:
        #! Force delete PVCs, since StatefulSet does not delete them
        rawOptions:
        - --apply-ignored=true