#@ load("@ytt:data", "data")
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflared
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudflared
  name: cloudflared
  namespace: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - args:
        - access
        - tcp
        - --hostname
        - #@ data.values.public_hosts.minecraft
        - --url
        - 0.0.0.0:25565
        image: cloudflare/cloudflared:latest
        name: cloudflared-minecraft
        ports:
        - name: minecraft
          containerPort: 25565
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    oci-network-load-balancer.oraclecloud.com/is-preserve-source: "true"
    oci-network-load-balancer.oraclecloud.com/security-list-management-mode: All
    oci.oraclecloud.com/load-balancer-type: nlb
  name: cloudflared
  namespace: cloudflared
spec:
  externalTrafficPolicy: Local
  ports:
  - name: minecraft
    port: 25565
    targetPort: minecraft
  selector:
    app: cloudflared
  type: LoadBalancer
