#@ load("@ytt:data", "data")
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflared
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudflared
  name: cloudflared
  namespace: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: cloudflared
  template:
    metadata:
      labels:
        pod: cloudflared
    spec:
      containers:
      - args:
        - access
        - tcp
        - --hostname
        - #@ data.values.public_hosts.minecraft
        - --url 0.0.0.0:25565
        image: cloudflare/cloudflared:latest
        name: cloudflared-minecraft