#@ load("@ytt:data", "data")
apiVersion: v1
kind: Secret
metadata:
  name: prometheus
  namespace: grafana
stringData:
  username: #@ data.values.prometheus.username
  password: #@ data.values.prometheus.password
type: Opaque
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
  namespace: grafana
spec:
  valuesFrom:
  - targetPath: basicAuthUser
    valueFrom:
      secretKeyRef:
        name: prometheus
        key: username
  - targetPath: secureJsonData.basicAuthPassword
    valueFrom:
      secretKeyRef:
        name: prometheus
        key: password
  instanceSelector:
    matchLabels:
      app.kubernetes.io/part-of: grafana
  datasource:
    name: prometheus
    type: prometheus
    access: proxy
    basicAuth: true
    url: #@ data.values.prometheus.url
    isDefault: true
    basicAuthUser: ${username}
    jsonData:
      tlsSkipVerify: false
      timeInterval: "5s"
      exemplarTraceIdDestinations:
      - name: trace_id
        datasourceUid: tempo
    secureJsonData:
      basicAuthPassword: ${password}
