expose:
  type: loadBalancer
  tls:
    certSource: secret
    secret:
      secretName: harbor-tls
  loadBalancer:
    IP: 192.168.11.215
externalURL: https://harbor.ik.am
persistence:
  persistentVolumeClaim:
    registry:
      size: 200Gi