#@ load("@ytt:data", "data")
apiVersion: v1
kind: Service
metadata:
  name: note-api
  namespace: note
  annotations:
    kapp.k14s.io/change-group: workload
  labels:
    app: note-api
    app.kubernetes.io/part-of: note-api
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: note-api
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-api
  namespace: note
  annotations:
    kapp.k14s.io/change-group: workload
  labels:
    app: note-api
    app.kubernetes.io/part-of: note-api
spec:
  replicas: #@ data.values.replicas
  selector:
    matchLabels:
      app: note-api
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
        github.com/revision: #@ data.values.git_revision
        instrumentation.opentelemetry.io/inject-java: opentelemetry/only-logs
      labels:
        app: note-api
        app.kubernetes.io/part-of: note-api
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -XX:ActiveProcessorCount=2 -XX:MaxMetaspaceSize=128M -XX:ReservedCodeCacheSize=32M -Xss512k -Dfile.encoding=UTF-8 -Dmanagement.endpoint.health.probes.add-additional-paths=true -Dmanagement.endpoint.health.show-details=always -Dmanagement.endpoints.web.exposure.include=info,health,prometheus -Dmanagement.health.probes.enabled=true -Dserver.port=8080 -Duser.country=JP -Duser.language=ja -Duser.timezone=Asia/Tokyo
        - name: BPL_JVM_THREAD_COUNT
          value: "28"
        - name: entry.api-url
          value: ${k8s.bindings.note-config.entry-api-url}
        - name: entry.client-id
          value: ${k8s.bindings.note-config.entry-api-client-id}
        - name: entry.client-secret
          value: ${k8s.bindings.note-config.entry-api-client-secret}
        - name: rsa.private-key
          value: file:/bindings/note-config/rsa-private-key.pem
        - name: rsa.public-key
          value: file:/bindings/note-config/rsa-public-key.pem
        - name: spring.sendgrid.api-key
          value: ${k8s.bindings.note-config.sendgrid-api-key}
        - name: management.zipkin.tracing.endpoint
          value: http://otel-collector.opentelemetry.svc.cluster.local:4318/v1/traces
        - name: management.opentelemetry.resource-attributes.k8s.pod.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: management.opentelemetry.resource-attributes.k8s.namespace.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: management.opentelemetry.resource-attributes.k8s.node.name
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: management.opentelemetry.resource-attributes.host.ip
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: spring.datasource.hikari.maximum-pool-size
          value: "4"
        - name: spring.datasource.hikari.minimum-idle
          value: "2"
        - name: spring.datasource.hikari.login-timeout
          value: "2"
        - name: spring.datasource.hikari.connection-timeout
          value: "2000"
        - name: spring.datasource.hikari.data-source-properties.cancelSignalTimeout
          value: "2"
        - name: spring.datasource.hikari.data-source-properties.connectTimeout
          value: "2"
        - name: spring.datasource.hikari.data-source-properties.loginTimeout
          value: "2"
        - name: spring.datasource.hikari.data-source-properties.socketTimeout
          value: "10"
        #! #! https://stackoverflow.com/a/57070517 for pgbouncer
        #! - name: spring.datasource.hikari.data-source-properties.prepareThreshold
        #!   value: "0"
        image: #@ data.values.image
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /livez
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
            scheme: HTTP
        startupProbe:
          httpGet:
            path: /readyz
            port: 8080
            scheme: HTTP
          failureThreshold: 20
          periodSeconds: 5
        name: workload
        ports:
        - containerPort: 8080
          name: user-port
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1002
          seccompProfile:
            type: RuntimeDefault
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: note-api
              topologyKey: kubernetes.io/hostname
            weight: 1