apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: gateway-crd
  namespace: app-install
  annotations:
    kapp.k14s.io/change-group: "{name}"
spec:
  serviceAccountName: kapp
  fetch:
  - http:
      url: https://raw.githubusercontent.com/projectcontour/contour/v1.30.0/examples/gateway/00-crds.yaml
  syncPeriod: 24h
  template:
  - ytt: { }
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true