apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: opentelemetry-operator
  namespace: app-install
  annotations:
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order: "upsert after upserting cert-manager"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting cert-manager"
spec:
  serviceAccountName: kapp
  fetch:
  - http:
      url: https://github.com/open-telemetry/opentelemetry-operator/releases/download/v0.104.0/opentelemetry-operator.yaml
  syncPeriod: 24h
  template:
  - ytt: { }
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true