apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: opentelemetry-operator
  namespace: app-install
  annotations:
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order: "upsert after upserting cert-manager"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting cert-manager"
spec:
  serviceAccountName: kapp
  fetch:
  - http:
      url: https://github.com/open-telemetry/opentelemetry-operator/releases/download/v0.114.0/opentelemetry-operator.yaml
  syncPeriod: 24h
  template:
  - ytt:
      inline:
        paths:
          overlay.yml: |
            #@ load("@ytt:overlay", "overlay")
            #@overlay/match by=overlay.subset({"kind":"Deployment","metadata":{"name":"opentelemetry-operator-controller-manager"}})
            ---
            spec:
              template:
                spec:
                  containers:
                  #@overlay/match by=overlay.all, expects="1+"
                  - resources:
                      #@overlay/match missing_ok=True
                      #@overlay/remove
                      limits:
                      #@overlay/match missing_ok=True
                      #@overlay/remove
                      requests:
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true