apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: contour
  namespace: app-install
  annotations:
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order: "upsert after upserting cert-manager"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting cert-manager"
spec:
  serviceAccountName: kapp
  fetch:
  - helmChart:
      name: contour
      version: 18.2.10
      repository:
        url: oci://registry-1.docker.io/bitnamicharts
  - http:
      url: https://raw.githubusercontent.com/projectcontour/contour/v1.29.1/examples/gateway/00-crds.yaml
  - git:
      url: https://github.com/making/k8s-gitops.git
      ref: origin/main
      subPath: plum/platform/contour
  syncPeriod: 24h
  template:
  - helmTemplate:
      name: contour
      namespace: projectcontour
      path: "0"
      valuesFrom:
      - path: 1/helm-values.yaml
  - ytt:
      paths:
      - '-'
      - '1'
      - 2/config
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true
      delete:
        #! Force delete PVCs, since StatefulSet does not delete them
        rawOptions:
        - --apply-ignored=true