apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-tls
  namespace: projectcontour
spec:
  dnsNames:
  - "*.ik.am"
  - "*.apricot.ik.am"
  - "*.lan.ik.am"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: default-tls
---
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: contour-delegation
  namespace: projectcontour
spec:
  delegations:
  - secretName: default-tls
    targetNamespaces:
    - "*"