#!/usr/bin/env bash
# Build a custom Traefik image with experimental.plugins (from helm-values.yaml)
# pre-installed under /plugins-local/src/. Also regenerates the ytt overlay that
# rewrites the Helm-rendered Deployment to use the custom image and switches
# experimental.plugins → experimental.localPlugins (no startup download).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
HELM_VALUES="${SCRIPT_DIR}/helm-values.yaml"
APP_FILE="${REPO_ROOT}/lemon/platform/_apps/traefik.yaml"
DOCKERFILE="${SCRIPT_DIR}/Dockerfile.generated"
OVERLAY_FILE="${SCRIPT_DIR}/config/local-plugins-overlay.yaml"

YQ_IMAGE="mikefarah/yq:4"
IMAGE_REPO="ghcr.io/making/traefik"
TAG_OVERRIDE=""
TRAEFIK_VERSION_OVERRIDE=""
PUSH=0
MULTI_ARCH=0
VERIFY=1

usage() {
  cat <<EOF
Usage: $(basename "$0") [--push] [--multi-arch] [--no-verify]
                       [--traefik-version=<vX.Y.Z>] [--image=<repo>] [--tag=<tag>]

Default: build for the host architecture, --load into the local docker daemon,
then verify by inspecting the image and booting traefik briefly.

  --push              push the resulting image (single-arch) to the registry
                      instead of --load
  --multi-arch        build linux/amd64 + linux/arm64 and push as a manifest
                      list — requires --push and creates a 'traefik-image-builder'
                      buildx builder (docker-container driver) on first use
  --no-verify         skip the post-build verification (--load mode only)
  --traefik-version=  override the base traefik tag (default: derived from
                      _apps/traefik.yaml chart version → Chart.yaml appVersion)
  --image=            override image repository (default: ${IMAGE_REPO})
  --tag=              override tag (default: <traefik-version>-<plugin-hash>)
EOF
}

for arg in "$@"; do
  case "$arg" in
    --push) PUSH=1 ;;
    --multi-arch) MULTI_ARCH=1 ;;
    --no-verify) VERIFY=0 ;;
    --traefik-version=*) TRAEFIK_VERSION_OVERRIDE="${arg#*=}" ;;
    --image=*) IMAGE_REPO="${arg#*=}" ;;
    --tag=*) TAG_OVERRIDE="${arg#*=}" ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $arg" >&2; usage; exit 1 ;;
  esac
done

yq() {
  docker run --rm -i "${YQ_IMAGE}" "$@"
}

# 1. Resolve the Traefik base image version
if [[ -n "${TRAEFIK_VERSION_OVERRIDE}" ]]; then
  TRAEFIK_VERSION="${TRAEFIK_VERSION_OVERRIDE}"
else
  CHART_VERSION="$(yq '.spec.fetch[] | select(has("helmChart")) | .helmChart.version' < "${APP_FILE}" | tr -d '\r' | head -1)"
  if [[ -z "${CHART_VERSION}" || "${CHART_VERSION}" = "null" ]]; then
    echo "ERROR: Could not determine helm chart version from ${APP_FILE}" >&2
    exit 1
  fi
  CHART_URL="https://raw.githubusercontent.com/traefik/traefik-helm-chart/v${CHART_VERSION}/traefik/Chart.yaml"
  TRAEFIK_VERSION="$(curl -fsSL "${CHART_URL}" | yq '.appVersion' | tr -d '\r' | head -1)"
  if [[ -z "${TRAEFIK_VERSION}" || "${TRAEFIK_VERSION}" = "null" ]]; then
    echo "ERROR: Could not fetch appVersion from ${CHART_URL}" >&2
    exit 1
  fi
  echo ">>> Detected traefik chart=${CHART_VERSION}, appVersion=${TRAEFIK_VERSION}"
fi

# 2. Extract plugins from helm-values.yaml as TSV: name<TAB>moduleName<TAB>version
PLUGIN_TSV="$(yq -o=tsv '.experimental.plugins | to_entries | .[] | [.key, .value.moduleName, .value.version]' < "${HELM_VALUES}" | sed '/^$/d')"
if [[ -z "${PLUGIN_TSV}" ]]; then
  echo "ERROR: No plugins found in ${HELM_VALUES} under .experimental.plugins" >&2
  exit 1
fi
echo ">>> Plugins:"
echo "${PLUGIN_TSV}" | sed 's/^/    /'

# 3. plugin-hash = sha256(stable-joined-list)[0:7]
if command -v sha256sum >/dev/null 2>&1; then
  HASH_CMD="sha256sum"
else
  HASH_CMD="shasum -a 256"
fi
PLUGIN_HASH="$(echo "${PLUGIN_TSV}" | sort | awk -F '\t' '{printf "%s=%s@%s\n",$1,$2,$3}' | ${HASH_CMD} | cut -c1-7)"

if [[ -n "${TAG_OVERRIDE}" ]]; then
  TAG="${TAG_OVERRIDE}"
else
  TAG="${TRAEFIK_VERSION}-${PLUGIN_HASH}"
fi
IMAGE_REF="${IMAGE_REPO}:${TAG}"
echo ">>> Image: ${IMAGE_REF}"

# 4. Generate Dockerfile.generated
{
  cat <<EOF
# syntax=docker/dockerfile:1.6
# AUTO-GENERATED by lemon/platform/traefik/build-image.sh — do not edit by hand.
# Source: helm-values.yaml .experimental.plugins
FROM --platform=\$BUILDPLATFORM alpine:3.20 AS plugin-fetcher
RUN apk add --no-cache curl unzip ca-certificates
WORKDIR /work
RUN mkdir -p /plugins-local/src
EOF
  while IFS=$'\t' read -r name module version; do
    [[ -z "${name}" ]] && continue
    cat <<EOF

# --- ${name} (${module}@${version}) ---
RUN set -eux; \\
    curl -fsSL -o /work/p.zip \\
        'https://plugins.traefik.io/public/download/${module}/${version}'; \\
    rm -rf /work/extract; mkdir -p /work/extract; \\
    unzip -q /work/p.zip -d /work/extract; \\
    MANIFEST=\$(find /work/extract -type f -name .traefik.yml | head -1); \\
    if [ -z "\$MANIFEST" ]; then \\
        echo "ERROR: .traefik.yml not found in archive for ${module}@${version}" >&2; \\
        ls -laR /work/extract; \\
        exit 1; \\
    fi; \\
    SRC_DIR=\$(dirname "\$MANIFEST"); \\
    mkdir -p "/plugins-local/src/${module}"; \\
    cp -a "\$SRC_DIR/." "/plugins-local/src/${module}/"; \\
    test -f "/plugins-local/src/${module}/.traefik.yml"; \\
    rm -rf /work/p.zip /work/extract
EOF
  done <<< "${PLUGIN_TSV}"
  cat <<EOF

FROM traefik:${TRAEFIK_VERSION}
COPY --from=plugin-fetcher /plugins-local /plugins-local
EOF
} > "${DOCKERFILE}"
echo ">>> Wrote ${DOCKERFILE}"

# 5. Generate config/local-plugins-overlay.yaml
mkdir -p "$(dirname "${OVERLAY_FILE}")"
{
  cat <<EOF
#! AUTO-GENERATED by lemon/platform/traefik/build-image.sh — do not edit by hand.
#! Rewrites the Helm-rendered Traefik Deployment to use the pre-baked image
#! and switches experimental.plugins (download-at-startup) → experimental.localPlugins.
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind": "Deployment", "metadata": {"name": "traefik"}})
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by=overlay.subset({"name": "traefik"})
      - image: ${IMAGE_REF}
        args:
        #@overlay/match by=lambda i,l,r: l.startswith("--experimental.plugins."), expects="0+"
        #@overlay/remove
        - ""
EOF
  while IFS=$'\t' read -r name module version; do
    [[ -z "${name}" ]] && continue
    cat <<EOF
        #@overlay/append
        - "--experimental.localPlugins.${name}.moduleName=${module}"
EOF
  done <<< "${PLUGIN_TSV}"
} > "${OVERLAY_FILE}"
echo ">>> Wrote ${OVERLAY_FILE}"

# Resolve host platform for the default --load path so that `docker run` does not
# trigger qemu emulation (and so logs from the boot-check are not empty).
case "$(uname -m)" in
  arm64|aarch64) HOST_PLATFORM="linux/arm64" ;;
  x86_64|amd64) HOST_PLATFORM="linux/amd64" ;;
  *) HOST_PLATFORM="linux/amd64" ;;
esac

# 6. docker buildx
BUILDX_ARGS=(buildx build --file "${DOCKERFILE}" --tag "${IMAGE_REF}")
if [[ "${MULTI_ARCH}" = "1" ]]; then
  if [[ "${PUSH}" != "1" ]]; then
    echo "ERROR: --multi-arch requires --push (multi-platform images cannot be loaded into the local docker daemon)." >&2
    exit 1
  fi
  # Multi-platform build needs a docker-container (or kubernetes) driver — the
  # default docker driver cannot produce a manifest list. Create a dedicated
  # builder once and reuse it.
  BUILDER_NAME="traefik-image-builder"
  if ! docker buildx inspect "${BUILDER_NAME}" >/dev/null 2>&1; then
    echo ">>> Creating buildx builder '${BUILDER_NAME}' (docker-container driver)"
    docker buildx create --name "${BUILDER_NAME}" --driver docker-container --bootstrap >/dev/null
  fi
  BUILDX_ARGS+=(--builder "${BUILDER_NAME}" --platform linux/amd64,linux/arm64 --push)
else
  BUILDX_ARGS+=(--platform "${HOST_PLATFORM}")
  if [[ "${PUSH}" = "1" ]]; then
    BUILDX_ARGS+=(--push)
  else
    BUILDX_ARGS+=(--load)
  fi
fi
BUILDX_ARGS+=("${SCRIPT_DIR}")

echo ">>> docker ${BUILDX_ARGS[*]}"
docker "${BUILDX_ARGS[@]}"

# 7. Verify (only when the image is loaded into the local daemon)
if [[ "${VERIFY}" = "1" && "${PUSH}" = "0" && "${MULTI_ARCH}" = "0" ]]; then
  echo ">>> Verifying plugin files in ${IMAGE_REF}"
  while IFS=$'\t' read -r name module version; do
    [[ -z "${name}" ]] && continue
    if docker run --rm --entrypoint sh "${IMAGE_REF}" \
         -c "test -f /plugins-local/src/${module}/.traefik.yml"; then
      echo "  OK: /plugins-local/src/${module}/.traefik.yml"
    else
      echo "  FAIL: /plugins-local/src/${module}/.traefik.yml" >&2
      exit 1
    fi
  done <<< "${PLUGIN_TSV}"

  echo ">>> Booting traefik briefly to confirm plugin load"
  EXTRA_ARGS=()
  while IFS=$'\t' read -r name module version; do
    [[ -z "${name}" ]] && continue
    EXTRA_ARGS+=("--experimental.localPlugins.${name}.moduleName=${module}")
  done <<< "${PLUGIN_TSV}"

  CONTAINER=$(docker run -d "${IMAGE_REF}" \
    --log.level=INFO \
    --api.insecure=true \
    --entryPoints.web.address=:8000 \
    "${EXTRA_ARGS[@]}")
  sleep 8
  LOGS=$(docker logs "${CONTAINER}" 2>&1 || true)
  docker rm -f "${CONTAINER}" >/dev/null 2>&1 || true
  echo "----- traefik logs (tail) -----"
  echo "${LOGS}" | tail -20
  echo "-------------------------------"
  if echo "${LOGS}" | grep -qE 'unable to (load|fetch|read|build) plugin|plugin .*not found|level=fatal|FTL|panic:'; then
    echo "FAIL: plugin load error detected in logs" >&2
    exit 1
  fi
  if ! echo "${LOGS}" | grep -q 'Plugins loaded'; then
    echo "FAIL: 'Plugins loaded' line not found in traefik logs" >&2
    exit 1
  fi
  echo ">>> Verification OK (Plugins loaded confirmed)"
elif [[ "${VERIFY}" = "1" ]]; then
  echo ">>> Skipping in-container verification (multi-arch or push mode — image not loaded locally)"
fi

osascript -e "display notification \"build complete: ${IMAGE_REF}\" with title \"traefik image baker\"" 2>/dev/null || true
echo ">>> Done: ${IMAGE_REF}"
