apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-tls
  namespace: harbor
spec:
  dnsNames:
  - harbor.ik.am
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: harbor-tls