installCRDs: true
metrics:
  enabled: false
controller:
  image:
    repository: bitnamilegacy/cert-manager
  acmesolver:
    image:
      repository: bitnamilegacy/acmesolver
webhook:
  image:
    repository: bitnamilegacy/cert-manager-webhook
cainjector:
  image:
    repository: bitnamilegacy/cainjector