image:
  repository: osixia/phpldapadmin
  tag: 0.9.0
  pullPolicy: IfNotPresent
ingress:
  enabled: true
  annotations:
    projectcontour.io/tls-cert-namespace: projectcontour
  hosts:
  - phpldapadmin.ik.am
  tls:
  - secretName: default-tls-ik-am
    hosts:
    - phpldapadmin.ik.am
service:
  type: ClusterIP
env:
  PHPLDAPADMIN_HTTPS: "false"
  PHPLDAPADMIN_TRUST_PROXY_SSL: "true"
  PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'ldap.ik.am': [{'server': [{'tls': 'true'}]}]}]"
