image:
  repository: osixia/phpldapadmin
  tag: 0.9.0
  pullPolicy: IfNotPresent
ingress:
  enabled: false
service:
  type: ClusterIP
env:
  PHPLDAPADMIN_HTTPS: "false"
  PHPLDAPADMIN_TRUST_PROXY_SSL: "true"
  PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'ldap.ik.am': [{'server': [{'tls': 'false'},{'port': 636},{'tls_reqcert','never'}]}]}]"
  PHPLDAPADMIN_LDAP_CLIENT_TLS_REQCERT: "never"