apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: contour-selfsigned-ca-issuer
  namespace: projectcontour
spec:
  selfSigned: { }
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: contour-ca
  namespace: projectcontour
spec:
  commonName: Contour CA
  dnsNames:
  - contourca
  duration: 8760h0m0s
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: contour-selfsigned-ca-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: 360h0m0s
  secretName: contour-ca-key-pair
  subject:
    organizations:
    - Project Contour
  usages:
  - server auth
  - client auth
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: contour-ca-issuer
  namespace: projectcontour
spec:
  ca:
    secretName: contour-ca-key-pair
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: contour-cert
  namespace: projectcontour
spec:
  commonName: contour
  dnsNames:
  - contour
  - contour.projectcontour
  - contour.projectcontour.svc
  - contour.projectcontour.svc.cluster.local
  duration: 8760h0m0s
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: contour-ca-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: 360h0m0s
  secretName: contourcert
  subject:
    organizations:
    - Project Contour
  usages:
  - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: envoy-cert
  namespace: projectcontour
spec:
  commonName: envoy
  dnsNames:
  - contour-envoy
  - contour-envoy.projectcontour
  - contour-envoy.projectcontour.svc
  - contour-envoy.projectcontour.svc.cluster.local
  duration: 8760h0m0s
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: contour-ca-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: 360h0m0s
  secretName: envoycert
  subject:
    organizations:
    - Project Contour
  usages:
  - client auth