apiVersion: ENC[AES256_GCM,data:M80=,iv:zY0rW+H7Zm/flHdz72UwgBiBFEHNUU9QARYv/iwicfk=,tag:X9OuA1Sv9gFo744nEqXtQg==,type:str]
kind: ENC[AES256_GCM,data:D1JtIwmq,iv:mQP+OJ+aZ0cfIRPAvIIa0/LT/iHJ8E2qo1oz14cbIjc=,tag:eA6p8CUq5AF3mDRh7GdNsw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ULLg+oR++GPUTevZ,iv:HU5YAekSO0F0OcNGFFHKyl9Sn0TlgetRNi1OJ7/CyQ0=,tag:zvhbXB/ZPPHoRYaB9/iCzQ==,type:str]
    namespace: ENC[AES256_GCM,data:uqdD5Hyd,iv:VfviODh1yW5JZItsqL+StPhmvV1y60f+aJykBKO905Q=,tag:lrx4AMDvdrRILsI/AI00Dg==,type:str]
stringData:
    token: ENC[AES256_GCM,data:UORUgLyBkNy0b5xTw5TZnAcG7n5OzWPPW256z6VYNrGZ7EiC,iv:C7lYsUK/NFa8doo4vVJVHBxbIqFSvXUL7WhAluk+TI8=,tag:n3bZt7s4NcE/ARKhPpzWhg==,type:str]
    username: ENC[AES256_GCM,data:VSpwxpC+XxdRwOz4,iv:Fb8fdHxonjJ9L4xRLo6XDcRrcaP+JzFpUjhvrL5svx8=,tag:/eg6h0b6TOoZyG2Njtih/A==,type:str]
    password: ENC[AES256_GCM,data:HIrDVLrpwX/ADQd0wgopllaVFdPU64UpG9pa8cduf5fEFVXd,iv:a4ZszuFgrxz1IDDLDPu62GAk93rp0qwY6J3LodBD1ic=,tag:NOomlj6a/xob0ZBU9/9M9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ej7fjm78n44tz3jnr6hkzhraf97egzekjfy87rfmhlnv9flwy55se0c5gz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZlczY0lVNU5vVXp6OU9n
            NTVLSENRUUdONC9KWWpGeENQUkFUQkg3N3lVCnZqNzUrajFGS1BvNmlEYmF3V0xP
            Qk5LdGNmQlpPQ0RlbFZ0ckxZdEhhaGcKLS0tIEN2Y2U2a3Fnak5QN0ZteEF6Vk16
            Z1J1K2lFYUNicnplMW5SMGp4R0IxZU0Ku/IT/RRgXxLZSgaDBiDnYqLAvEb5JHpm
            UusPbaVr62thmYW+2K2feVXGuaChAGgDVmGvV7IyqGfyTxiAr8ql+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-10T12:25:19Z"
    mac: ENC[AES256_GCM,data:n3f39UK+3jz/u/3R3SGJAfgwxJ+Ufjwu9nKXaUjnaHTmhixV/8A3kCLUdz8HhqEV5/j17FzzbPb0BTxHiiVudLzAByzedMh5vLU1tt1AGUAqYSYa63SznSfjki/IGaL+UViZIVFCmxm4YbTibH6b7VdOfv0Yq4hE0mjRasOzTrY=,iv:+LI3SosYeWpD6I96JQnWQR7+P6Ct+QkZuiBYuwui9YM=,tag:KGm991O08LZyMm89eIa9lA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
