apiVersion: ENC[AES256_GCM,data:Vno=,iv:Rq5cMsE8+KBn3kmhKJa1mxdXICBrbwQhhHeI7UvUyGI=,tag:n5XCWa0uMFIN/9ltdR6Xtw==,type:str]
kind: ENC[AES256_GCM,data:YprIambg,iv:dWZVbAbSCYsas7OkgIf9tD5mABoj3VjlLAb7aZMwwFQ=,tag:UG/gt3uiZ6JziyLDsAXYeg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:CsdMSoGblTaoO7GF,iv:O5s7nydt8SMbqdyxjnWcYnK0FNkORreFh9o4WOsCpxo=,tag:DpCC5WG11DXRQKrpxoTriw==,type:str]
    namespace: ENC[AES256_GCM,data:aUi5NZ3Q,iv:ueu89NUJ2j/AMzz9ZPoKls9CYKvH5z3VCqp83w6v52E=,tag:vM+eBlQtVoFtdYj0Ioqxlg==,type:str]
stringData:
    token: ENC[AES256_GCM,data:wKkS3V29LjUQQZouTzsxm6cD+tSqN14XUKEANjxfdyS3IdLj,iv:zwa5btimGtcQbbDeijp1wXVVOJKyNcs+EN4lUkRa6YQ=,tag:wCvMamWtpErmav/y8pWWcQ==,type:str]
    username: ENC[AES256_GCM,data:NePtvOMiKzGEyz2M,iv:yGxL3papYfc8QjIc7WzYSAAklheyPIZxIAnKzTE5L9c=,tag:LJZOG2pI1P3h4a6khbVvWQ==,type:str]
    password: ENC[AES256_GCM,data:xxFXmFW5v7Y+STgKzDCPhcUsTVBcn3YKEKQFjy0nmQcjjOdEpxB5K4On,iv:jfyoxHZPGI6/hhaXH6fB7ymAt7IB73nGL99QvcIvtC4=,tag:ApTe3jW03/XI6PQkg65IdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ej7fjm78n44tz3jnr6hkzhraf97egzekjfy87rfmhlnv9flwy55se0c5gz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZXEvRlNON1EwYUJQRFJp
            b1d3Vkl6ejdWYmhTWml0R3k4Zll0SHpGU1M0CklHMEZqVWNET05NK0dIbStwSS9B
            ZjRSM2wyM3F6ZWdYcVFSbEtvcFV6Yk0KLS0tIGFVK3Z0Y3FHQXJLZXhjeVJ2N3A5
            RkU3Q1IyZnFSdUtKRWU3UUk4bzJnNUUKsrna7HgPGPRbIZlfWIBUXjzuoZJTDs8M
            JTzfbr6gV5Aw5YOxrl8RzhFhtfF2N0JjnXrFDWz+lrhmv1gYBxKfcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-10T12:39:19Z"
    mac: ENC[AES256_GCM,data:R8351xdUU7AQWhiYtSy76bFNjoRPR0RMKUk8ukR9DhBYQO3B/lUNrQQJXfSHAhSXnFsrX8C1N2YSVOZ/PzImGKnbmdGnoqLi1/RmNnNB/DgOdZUz5VmRA0cLnNGWm44pg6mooJz8ATMWKLwb4S0Q1ULVY97T2EFCUHCRMYSjSTM=,iv:XyoaOTfJhPrliIUAadMasSMQhtF1R7TiWs3EbOCBeB4=,tag:kyLfFH27GiTgu45CeKbNcQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
