apiVersion: ENC[AES256_GCM,data:IRM=,iv:qmTvaxM3njBJRcTqKtgDkeT9Wvj9qQeiQty+zsvyybw=,tag:8XT6ckzgduD33ADkJoDsvQ==,type:str]
kind: ENC[AES256_GCM,data:D4+ZHNEF,iv:yV+satwsWwHb7sqcvbXE7xL0Lo4VZu3jmwzEgy2lNPs=,tag:NvECdHG44lIFRRuWQdI3Eg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dBh5vPHDjb2x16K4,iv:wJzGIs3uqiT6q05kgR1IW5cL/eX+UuTcXDME83VMXY4=,tag:NBHJNdSQACXhTnasJ6qmbQ==,type:str]
    namespace: ENC[AES256_GCM,data:Fewc4OPp,iv:1P0JsoubKfzlds/LiQF4d3NtEEqwgMc6OujY23EsI80=,tag:WOyqA19iu3hyAPMc+kN1Rw==,type:str]
stringData:
    token: ENC[AES256_GCM,data:4LSJAbAWUtMvEJG09MS47IET2IsQ1e+gsbCINn4XDHxHAfQI,iv:d+WojHo6nOuweEyVTwtMgbEk4NeS53HE43l7NiPXmb8=,tag:Pm/USWrTfQ50VtCdlG5rcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ej7fjm78n44tz3jnr6hkzhraf97egzekjfy87rfmhlnv9flwy55se0c5gz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SFRvVDg1OUxaZ2d2Ujdz
            UlVidHlYbDA3ZEk0Y0x0b3IzUFdzMnRqckJFCjcyK3AvS1J3TElvYmpURlNrVEJQ
            N3NLMmljRXg3ZDNpOUpsemhzcEVLV3cKLS0tIERzQkhKbzg3NUM1TnpBU2hDdE9H
            YWJqNUp6K0x0bC83UlFTa1pzWEJVODgKaYBAAcqH8DVXJB6/SrJuZl9A2c0EHsgR
            8j2bLO8bK3h6Be4UMUX+0WCnCWB6RE5OJb0nnLcSdaGEvqJ/bXAKTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-10T01:06:10Z"
    mac: ENC[AES256_GCM,data:aKHUPl9tijEpkU9yK8r7uhKCG+bMYZu7LOxKCAi3S6oKF61YEuQBq0brYBii1G+w/jrUW+2mttg5LkQhL4gUWbOgNJZ0XvdZNCwqY0AsU+Me/qYAeyybhz8CmlGJpqGFDdR1fl/3nUDmgcSxosjOfjwpAour6wXopFqkMbWl76E=,iv:vPGbXInMqkgafBWtnt4aiDneBOnFi2EgbmW34/frVdc=,tag:SlbFGc9iyov4SJBNn/sVNw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
