service:
  type: ClusterIP
extraEnvVars:
- name: MODULE_OPTS
  value: "-Dloader.path=/modules/otel -Dspring.profiles.active=otel"
initContainers:
- name: download-modules
  image: nicolaka/netshoot
  command: [ "sh" ]
  args:
  - -cex
  - |
    curl -sSL https://zipkin.io/quickstart.sh | bash -s io.zipkin.contrib.otel:zipkin-module-otel:LATEST:module otel.jar
    mkdir -p /modules/otel
    mv otel.jar /modules/otel/
  volumeMounts:
  - name: modules
    mountPath: /modules
- name: unjar-modules
  image: bitnami/java
  command: [ "sh" ]
  args:
  - -cex
  - |
    cd /modules/otel
    jar -xf otel.jar
    rm -f otel.jar
  volumeMounts:
  - name: modules
    mountPath: /modules
extraVolumes:
- name: modules
  emptyDir: { }
extraVolumeMounts:
- name: modules
  mountPath: /modules
cassandra:
  persistence:
    storageClass: nfs