#@ load("@ytt:data", "data")
apiVersion: v1
kind: Secret
metadata:
  name: translation-config
type: Opaque
stringData:
  type: "translation-api"
  openai-api-key: #@ data.values.openai_api_key
  github-access-token: #@ data.values.github_access_token
  github-webhook-secret: #@ data.values.github_webhook_secret
  otlp-logs-endpoint: #@ data.values.otlp_logs_endpoint
  otlp-logs-header-authorization: #@ data.values.otlp_logs_header_authorization
  otlp-traces-endpoint: #@ data.values.otlp_traces_endpoint
  otlp-traces-header-authorization: #@ data.values.otlp_traces_header_authorization
