#@ load("@ytt:data", "data")
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: translation-api
  labels:
    app: translation-api
    app.kubernetes.io/part-of: translation-api
spec:
  template:
    metadata:
      annotations:
        github.com/revision: #@ data.values.git_revision
    spec:
      containers:
      - image: #@ data.values.image
        imagePullPolicy: IfNotPresent
        env:
        - name: server.port
          value: "8080"
        - name: info.env.hostname
          value: ${HOSTNAME:}
        - name: entry.api-url
          value: https://blog-api-blog.apps.ik.am
        - name: spring.ai.openai.api-key
          valueFrom:
            secretKeyRef:
              key: openai-api-key
              name: translation-config
        - name: github.access-token
          valueFrom:
            secretKeyRef:
              key: github-access-token
              name: translation-config
        - name: github.webhook-secret
          valueFrom:
            secretKeyRef:
              key: github-webhook-secret
              name: translation-config
        - name: management.otlp.logging.endpoint
          valueFrom:
            secretKeyRef:
              key: otlp-logs-endpoint
              name: translation-config
        - name: management.otlp.logging.headers.authorization
          valueFrom:
            secretKeyRef:
              key: otlp-logs-header-authorization
              name: translation-config
        - name: management.otlp.tracing.endpoint
          valueFrom:
            secretKeyRef:
              key: otlp-traces-endpoint
              name: translation-config
        - name: management.otlp.tracing.headers.authorization
          valueFrom:
            secretKeyRef:
              key: otlp-traces-header-authorization
              name: translation-config
        - name: management.otlp.metrics.export.url
          valueFrom:
            secretKeyRef:
              key: otlp-metrics-endpoint
              name: translation-config
        - name: management.otlp.metrics.export.headers.authorization
          valueFrom:
            secretKeyRef:
              key: otlp-metrics-header-authorization
              name: translation-config
        - name: management.otlp.metrics.export.step
          value: 10s
        - name: management.otlp.metrics.export.base-time-unit
          value: seconds
        - name: management.metrics.tags.app
          value: translation-api
        - name: management.metrics.tags.cluster
          value: zje2gl28i8h
        - name: management.metrics.tags.instance
          value: ${HOSTNAME:}
        - name: management.metrics.tags.namespace
          value: zje2gl28i8h
        - name: management.metrics.tags.pod
          value: ${HOSTNAME:}
        - name: management.opentelemetry.resource-attributes.k8s.pod.name
          value: ${HOSTNAME:}
        - name: management.opentelemetry.resource-attributes.k8s.namespace.name
          value: zje2gl28i8h
        - name: management.opentelemetry.resource-attributes.k8s.cluster.name
          value: zje2gl28i8h
        - name: logging.structured.format.console
          value: ecs
        - name: spring.threads.virtual.enabled
          value: "true"
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 125m
            ephemeral-storage: 400M
            memory: 250M
          requests:
            cpu: 125m
            ephemeral-storage: 400M
            memory: 250M
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1002
          seccompProfile:
            type: RuntimeDefault
        livenessProbe:
          httpGet:
            path: /livez
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 1
        startupProbe:
          httpGet:
            path: /readyz
            port: 8080
          failureThreshold: 20
          periodSeconds: 5
          timeoutSeconds: 1
