applicationName: httpbin
deployment:
  image:
    repository: ghcr.io/mccutchen/go-httpbin
    tag: latest
    pullPolicy: Always
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  resources:
    limits:
      cpu:
      memory: 32Mi
    requests:
      cpu:
      memory: 32Mi
  containerSecurityContext:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    #! traefik.ingress.kubernetes.io/router.middlewares: traefik-headers-middleware@kubernetescrd
  hosts:
  - host: httpbin.raspberry.ik.am
    paths:
    - path: /
      pathType: Prefix
  tls:
  - hosts:
    - httpbin.raspberry.ik.am
    secretName: httpbin-tls