#@ load("@ytt:data", "data")
apiVersion: v1
kind: Secret
metadata:
  name: counter-config
type: Opaque
stringData:
  jdbc-url: #@ data.values.jdbc_url
  jdbc-username: #@ data.values.jdbc_username
  jdbc-password: #@ data.values.jdbc_password
  otlp-logs-endpoint: #@ data.values.otlp_logs_endpoint
  otlp-logs-header-authorization: #@ data.values.otlp_logs_header_authorization
  otlp-traces-endpoint: #@ data.values.otlp_traces_endpoint
  otlp-traces-header-authorization: #@ data.values.otlp_traces_header_authorization
  otlp-metrics-endpoint: #@ data.values.otlp_metrics_endpoint
  otlp-metrics-header-authorization: #@ data.values.otlp_metrics_header_authorization