#@ load("@ytt:data", "data")
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: counter-api
  labels:
    app: counter-api
    app.kubernetes.io/part-of: counter-api
spec:
  template:
    metadata:
      annotations:
        github.com/revision: #@ data.values.git_revision
    spec:
      containers:
      - image: #@ data.values.image
        imagePullPolicy: IfNotPresent
        env:
        - name: RUST_LOG
          value: info
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: database-url
              name: counter-config
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 125m
            ephemeral-storage: 400M
            memory: 250M
          requests:
            cpu: 125m
            ephemeral-storage: 400M
            memory: 250M
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1002
          seccompProfile:
            type: RuntimeDefault
