minecraftServer:
  eula: "TRUE"
  type: "FORGE"
  version: "1.20.1"
  difficulty: easy
  gameMode: creative
  motd: "Welcome to Minecraft Forge on Kubernetes!"
  modUrls:
  - https://mediafilez.forgecdn.net/files/6045/363/hmag-forge-mc1.20.1-9.0.25.jar
  - https://mediafilez.forgecdn.net/files/5571/439/Siren_head%20v1.1.4-1.20.1.jar
  - https://mediafilez.forgecdn.net/files/5909/16/poppy_playtime_java-1.3-forge-1.20.1.jar
  - https://mediafilez.forgecdn.net/files/6027/567/geckolib-forge-1.20.1-4.7.jar
  - https://mediafilez.forgecdn.net/files/5789/363/journeymap-1.20.1-5.10.3-forge.jar
  - https://mediafilez.forgecdn.net/files/5911/986/framework-forge-1.20.1-0.7.12.jar
  - https://mediafilez.forgecdn.net/files/5893/833/refurbished_furniture-forge-1.20.1-1.0.8.jar
  - https://mediafilez.forgecdn.net/files/5891/357/grising-0.1.9-forge-1.20.1_patch.jar
  - https://mediafilez.forgecdn.net/files/5654/821/Kleiders%20Custom%20Renderer%20API%207.2.0%201.20.1.jar
  - https://mediafilez.forgecdn.net/files/5834/748/chucky-1.0.1-forge-1.20.1.jar
  #! - client only https://mediafilez.forgecdn.net/files/5838/485/Neat-1.20.1-41-FORGE.jar
  #! - client only https://github.com/Korea-Minecraft-Forum/CocoaInput/releases/download/4.3.1-0/CocoaInput-1.20.1-forge-4.3.1-EXPERIMENTAL.jar
  overrideServerProperties: true
  enforceSecureProfile: true
  serviceType: LoadBalancer
  externalTrafficPolicy: Local
  memory: 4096M
  jvmOpts: "-Dfile.encoding=UTF-8 -Duser.country=JP -Duser.language=ja -Duser.timezone=Asia/Tokyo -XX:+ExitOnOutOfMemoryError -XX:NativeMemoryTracking=summary"
  rcon:
    enabled: true
  vanillaTweaksShareCodes:
  - uRsiNA
  extraPorts:
  - name: webmap
    containerPort: 8080
    protocol: TCP
    service:
      enabled: true
      embedded: false
      port: 8080
extraEnv: { }
resources:
  requests:
    memory: 4.5Gi
persistence:
  storageClass: oci-bv
  dataDir:
    enabled: true
    Size: 50Gi
serviceAnnotations:
  oci-network-load-balancer.oraclecloud.com/is-preserve-source: "true"
  oci-network-load-balancer.oraclecloud.com/security-list-management-mode: All
  oci.oraclecloud.com/load-balancer-type: nlb
podAnnotations:
  instrumentation.opentelemetry.io/inject-java: opentelemetry/default