#@ load("@ytt:data", "data")
apiVersion: v1
kind: Secret
metadata:
  name: otel-creds
  namespace: opentelemetry
type: Opaque
stringData:
  aws_access_key_id: #@ data.values.s3.access_key_id
  aws_secret_access_key: #@ data.values.s3.access_secret