#@ load("@ytt:data", "data")
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-ik-am
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: makingx+peach@gmail.com
    privateKeySecretRef:
      name: letsencrypt-ik-am
    solvers:
    - dns01:
        azureDNS:
          clientID: #@ data.values.azure.client_id
          clientSecretSecretRef:
            name: azuredns-config
            key: client-secret
          subscriptionID: #@ data.values.azure.subscription_id
          tenantID: #@ data.values.azure.tenant_id
          resourceGroupName: ik-am
          hostedZoneName: ik.am
          environment: AzurePublicCloud
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-tls-ik-am
  namespace: projectcontour
spec:
  dnsNames:
  - "ik.am"
  - "*.ik.am"
  - "*.apps.ik.am"
  - "*.gw.ik.am"
  - "*.synology.ik.am"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-ik-am
  secretName: default-tls-ik-am