#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.subset({"kind":"ConfigMap", "metadata": {"name": "haproxy-config"}}), expects="0+"
---
metadata:
  annotations:
    #@overlay/match missing_ok=True
    kapp.k14s.io/versioned: ""