apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: demo-dsql-ik-am
  namespace: demo
spec:
  virtualhost:
    fqdn: demo-dsql.ik.am
    tls:
      secretName: projectcontour/default-tls-ik-am
  routes:
  - services:
    - name: demo-dsql
      port: 80