#@ load("@ytt:data", "data")
apiVersion: v1
kind: Service
metadata:
  name: demo-dsql
  namespace: demo
  annotations:
    kapp.k14s.io/change-group: workload
  labels:
    app: demo-dsql
    app.kubernetes.io/part-of: demo-dsql
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo-dsql
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-dsql
  namespace: demo
  annotations:
    kapp.k14s.io/change-group: workload
  labels:
    app: demo-dsql
    app.kubernetes.io/part-of: demo-dsql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-dsql
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
        github.com/revision: #@ data.values.git_revision
      labels:
        app: demo-dsql
        app.kubernetes.io/part-of: demo-dsql
    spec:
      containers:
      - env:
        - name: logging.structured.format.console
          value: ecs
        - name: info.env.hostname
          value: ${HOSTNAME:}
        image: #@ data.values.image
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /livez
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
            scheme: HTTP
        startupProbe:
          httpGet:
            path: /readyz
            port: 8080
            scheme: HTTP
          failureThreshold: 20
          periodSeconds: 5
        name: workload
        ports:
        - containerPort: 8080
          name: user-port
          protocol: TCP
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1002
          seccompProfile:
            type: RuntimeDefault
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: demo-dsql
              topologyKey: kubernetes.io/hostname
            weight: 1