#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind":"Deployment","metadata":{"name":"minecraft-minecraft"}})
---
spec:
  #@overlay/match missing_ok=True
  replicas: 0