#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.subset({"kind":"Deployment","metadata":{"name":"minecraft-minecraft"}})
---
spec:
  template:
    spec:
      #@overlay/match missing_ok=True
      initContainers:
      #@overlay/append
      - name: download-geyser-jar
        image: curlimages/curl:latest
        command:
        - sh
        - -c
        - |
          curl -L -o /app/Geyser.jar https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/standalone
        volumeMounts:
        - name: config-dir
          mountPath: /app
      containers:
      #@overlay/append
      - name: geyser
        image: roblkyogre/docker-geyser:20250101-121422
        ports:
        - name: geyser
          containerPort: 19132
          protocol: UDP
        env:
        - name: REMOTE_ADDRESS
          value: localhost
        - name: REMOTE_PORT
          value: "25565"
        volumeMounts:
        - name: config-dir
          mountPath: /app
      volumes:
      #@overlay/append
      - name: config-dir
        emptyDir: { }
#@overlay/match by=overlay.subset({"kind":"Service","metadata":{"name":"minecraft-minecraft"}})
---
spec:
  ports:
  #@overlay/append
  - name: geyser
    protocol: UDP
    port: 19132
    targetPort: geyser
