operator:
  enabled: false
prometheus:
  enabled: false
alertmanager:
  enabled: false
kubelet:
  enabled: false
blackboxExporter:
  enabled: false
kubeApiServer:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
coreDns:
  enabled: false
kubeProxy:
  enabled: false
node-exporter:
  podAnnotations:
    prometheus.io/scrape: "true"
  serviceMonitor:
    enabled: false
kube-state-metrics:
  podAnnotations:
    prometheus.io/scrape: "true"
  serviceMonitor:
    enabled: false