#@ load("@ytt:data", "data")
#@ if/end data.values.pdb:
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: comment-api
  namespace: blog
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: comment-api