apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-blocked-ips
  namespace: haproxy
  annotations:
    kapp.k14s.io/versioned: ""
data:
  blocked-ips.txt: |
    143.20.49.38/32
    34.159.25.14/32
    35.216.195.77/32
    36.133.83.220/32
    36.212.183.29/32
