apiVersion: v1
kind: Service
metadata:
  name: haproxy
  namespace: haproxy
spec:
  type: LoadBalancer
  ports:
  - name: ldaps
    port: 636
    targetPort: 636
    protocol: TCP
  - name: minecraft
    port: 25565
    targetPort: 25565
    protocol: TCP
  selector:
    app: haproxy