apiVersion: v1
kind: Service
metadata:
  name: haproxy
  namespace: haproxy
  annotations:
    oci-network-load-balancer.oraclecloud.com/is-preserve-source: "true"
    oci-network-load-balancer.oraclecloud.com/security-list-management-mode: All
    oci.oraclecloud.com/load-balancer-type: nlb
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  - name: ldaps
    port: 636
    targetPort: 636
    protocol: TCP
  - name: minecraft
    port: 25565
    targetPort: 25565
    protocol: TCP
  selector:
    app: haproxy