#@overlay/match by=overlay.subset({"kind":"Deployment","metadata":{"name":"openldap-stack-ha-ltb-passwd"}})
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by="name"
      - name: ltb-passwd
        #@overlay/match missing_ok=True
        env:
        #@overlay/match by="name", missing_ok=True
        - name: PASSWORD_MIN_LENGTH
          value: "8"
        #@overlay/match by="name", missing_ok=True
        - name: PASSWORD_MIN_DIGIT
          value: "1"
        #@overlay/match by="name", missing_ok=True
        - name: SECRETEKEY
          value: password
        #@overlay/match by="name", missing_ok=True
        - name: SMTP_HOST
          value: #@ data.values.smtp.hostname
        #@overlay/match by="name", missing_ok=True
        - name: SMTP_AUTH_ON
          value: "true"
        #@overlay/match by="name", missing_ok=True
        - name: SMTP_USER
          value: #@ data.values.smtp.username
        #@overlay/match by="name", missing_ok=True
        - name: SMTP_PASS
          value: #@ data.values.smtp.password
        #@overlay/match by="name", missing_ok=True
        - name: SMTP_PORT
          value: #@ data.values.smtp.port
        #@overlay/match by="name", missing_ok=True
        - name: SMTP_SECURE_TYPE
          value: "ssl"
        #@overlay/match by="name", missing_ok=True
        - name: SITE_URL
          value: https://ltb-passwd.ik.am
        #@overlay/match by="name", missing_ok=True
        - name: IS_BEHIND_PROXY
          value: "true"
        #@overlay/match by="name", missing_ok=True
        - name: SMTP_DEBUG
          value: "1"