apiVersion: v1
kind: ConfigMap
metadata:
  name: kapp-config
  namespace: blog
  labels:
    kapp.k14s.io/config: ""
data:
  config.yml: |
    apiVersion: kapp.k14s.io/v1alpha1
    kind: Config
    waitRules:
    - supportsObservedGeneration: true
      conditionMatchers:
      - type: ServiceAvailable
        status: "True"
        unblockChanges: true
      - type: Ready
        status: "False"
        failure: true
      - type: Ready
        status: "True"
        success: true
      resourceMatchers:
      - apiVersionKindMatcher: { apiVersion: servicebinding.io/v1, kind: ServiceBinding }