apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: valkey-secret
  namespace: access-monitor
spec:
  length: 24
  secretTemplate:
    type: Opaque
    stringData:
      valkey-password: $(value)