#@ load("@ytt:data", "data")
apiVersion: v1
kind: Secret
metadata:
  name: pgbackweb-secret
  namespace: pgbackweb
type: Opaque
stringData:
  PBW_ENCRYPTION_KEY: #@ data.values.pbw_encryption_key
  PBW_POSTGRES_CONN_STRING: #@ data.values.pbw_postgres_conn_string