apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: access-monitor-admin-user
  namespace: access-monitor
spec:
  length: 24
  secretTemplate:
    type: Opaque
    stringData:
      username: admin
      password: $(value)