#@ load("@ytt:data", "data")
apiVersion: v1
kind: Secret
metadata:
  name: access-monitor-config
  namespace: access-monitor
  annotations:
    kapp.k14s.io/versioned: ""
type: Opaque
stringData:
  github-access-token: #@ data.values.github_access_token
  allowed-ips: #@ data.values.allowed_ips
  admin-password: #@ data.values.admin_password