#@ load("@ytt:data", "data")
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: api-token
  namespace: inlets
spec:
  plugin:
    api-token:
      bearerHeader: true
      bearerHeaderName: Authorization
      removeHeadersOnSuccess: false
      tokens: #@ data.values.api_tokens
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oidc-auth-forge
  namespace: inlets
spec:
  plugin:
    oidc-auth:
      LogLevel: WARN
      forceHTTPS: "true"
      Provider:
        ClientId: #@ data.values.oidc.forge.client_id
        ClientSecret: #@ data.values.oidc.forge.client_secret
        Url: #@ data.values.oidc.provider_url
        UsePkce: true
      Headers:
      - Name: "Authorization"
        Value: "Bearer {{ .idToken }}"
      Scopes:
      - openid
      - profile
      - groups
      - email
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oidc-auth-vanilla
  namespace: inlets
spec:
  plugin:
    oidc-auth:
      LogLevel: WARN
      forceHTTPS: "true"
      Provider:
        ClientId: #@ data.values.oidc.vanilla.client_id
        ClientSecret: #@ data.values.oidc.vanilla.client_secret
        Url: #@ data.values.oidc.provider_url
        UsePkce: true
      Headers:
      - Name: "Authorization"
        Value: "Bearer {{ .idToken }}"
      Scopes:
      - openid
      - profile
      - groups
      - email