image:
  tag: multiarch
ingress:
  enabled: true
  annotations:
    projectcontour.io/tls-cert-namespace: projectcontour
    projectcontour.io/websocket-routes: /websocket
  host: rcon.lemon.maki.lol
  tls:
  - hosts:
    - rcon.lemon.maki.lol
    secretName: default-tls
rconWeb:
  isAdmin: true
  rconHost: minecraft-minecraft-rcon.minecraft.svc.cluster.local
  rconPasswordExistingSecret: "minecraft-minecraft-rcon"
  rconPasswordKey: "rcon-password"