{
 "title": "Fly App",
 "description": "General Fly App metrics.",
 "tags": [ "fly" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(fly_instance_up, app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data Out",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "label_uppercase(sum(rate(fly_edge_data_out{app=\"$app\"}[$__range]))by(region), \"region\") > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_uppercase(sum(rate(fly_instance_net_sent_bytes{app=\"$app\"}[$__range]))by(region), \"region\") > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Out",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk_avg(5, sum(rate(fly_edge_data_out{app=\"$app\"}[$__range]) > 0)by(region), \"region=other\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk_avg(5, sum(rate(fly_instance_net_sent_bytes{app=\"$app\"}[$__range]) > 0)by(region), \"region=other\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(fly_instance_net_recv_bytes{app=\"$app\",device=\"eth0\"}))",
     "legendFormat": "Total Received"
    },
    {
     "expr": "topk_avg(5,\n  sum(rate(fly_instance_net_recv_bytes\n    {app=~\"$app\",device=\"eth0\"}))by(instance,region)\n, \"region=Other\") > 0",
     "legendFormat": "{{instance}} - {{region}}"
    },
    {
     "expr": "sum(rate(fly_instance_net_sent_bytes{app=\"$app\",device=\"eth0\"}))",
     "legendFormat": "Total Sent"
    },
    {
     "expr": "topk_avg(5,\n  sum(rate(fly_instance_net_sent_bytes\n    {app=~\"$app\",device=\"eth0\"}))by(instance,region)\n, \"region=Other\") > 0",
     "legendFormat": "{{instance}} - {{region}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "description": "Top 10 instances",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mode(fly_instance_memory_mem_total{app=\"$app\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "fly_instance_memory_mem_total{app=\"$app\"} - fly_instance_memory_mem_available{app=\"$app\"}",
     "legendFormat": "{{instance}} - {{region}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "Top 10 instances",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(increase(fly_instance_cpu{app=\"$app\", mode!=\"idle\"}[60s]))by(instance, region)/60 / \n  sum(count(fly_instance_cpu{app=\"$app\", mode=\"idle\"})without(cpu))by(instance, region)",
     "legendFormat": "{{instance}} - {{region}}"
    }
   ]
  },
  {
   "title": "App Concurrency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(fly_app_concurrency{app=\"$app\"})by(instance, region)",
     "legendFormat": "{{instance}} - {{region}}"
    }
   ]
  },
  {
   "title": "5min Load Avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(fly_instance_load_average{app=\"$app\",minutes=\"5\"})by(instance, region) /\n  sum(count(fly_instance_cpu{app=\"$app\", mode=\"idle\"})without(cpu))by(instance, region)",
     "legendFormat": "{{instance}} - {{region}}"
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Response Count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(fly_app_http_responses_count{app=\"$app\"})) by (status) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Edge HTTP Response Count / Latency",
     "type": "geomap",
     "description": "* Size: Count\n* Color: Latency",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "label_uppercase(\n    sum(\n        increase(fly_edge_http_response_time_seconds_count{app=\"$app\"}[$__range])\n        )by(region,le) / \n    max(sum(\n        increase(fly_edge_http_response_time_seconds_count{app=\"$app\"}[$__range])\n        )by(region,le))\n    , \"region\")",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_uppercase(\n  sum(increase(\n    fly_edge_http_response_time_seconds_sum{app=\"$app\"}[$__range]\n    ))by(region) /\n  sum(increase(\n    fly_edge_http_response_time_seconds_count{app=\"$app\"}[$__range]\n    ))by(region)\n  , \"region\") * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP Response Times",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(increase(fly_app_http_response_time_seconds_sum{app=\"$app\"}))/sum(increase(fly_app_http_response_time_seconds_count{app=\"$app\"}))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantiles(\"p\", 0.5, 0.9, 0.99, sum(increase(fly_app_http_response_time_seconds_bucket{app=\"$app\"}))by(le))",
       "legendFormat": "p{{p}}"
      }
     ]
    },
    {
     "title": "HTTP Response Time Avg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(increase(fly_app_http_response_time_seconds_sum{app=\"$app\"}))by(instance,region)/sum(increase(fly_app_http_response_time_seconds_count{app=\"$app\"}))by(instance,region)",
       "legendFormat": "{{instance}} - {{region}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volume Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fly_instance_filesystem_blocks{app=~\"^$app$\", mount!=\"/\"} * fly_instance_filesystem_block_size{app=~\"^$app$\", mount!=\"/\"}",
       "legendFormat": "{{mount}} ({{instance}} - {{region}}) Total"
      },
      {
       "expr": "fly_instance_filesystem_blocks{app=~\"^$app$\", mount!=\"/\"} * fly_instance_filesystem_block_size{app=~\"^$app$\", mount!=\"/\"} - fly_instance_filesystem_blocks_avail{app=~\"^$app$\",mount!=\"/\"} * fly_instance_filesystem_block_size{app=~\"^$app$\",mount!=\"/\"}",
       "legendFormat": "{{mount}} ({{instance}} - {{region}}) Used"
      }
     ]
    }
   ]
  }
 ]
}