{
 "title": "Kubernetes Cluster",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info{cluster=\"$cluster\"},node)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created{cluster=\"$cluster\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", kubernetes_io_hostname=~\"$node\", namespace=~\"$namespace\", container!=\"\"}[5m]))",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(kube_node_status_capacity{cluster=\"$cluster\",node=~\"$node\", resource=\"cpu\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=\"$cluster\",node=~\"$node\", namespace=~\"$namespace\", resource=\"cpu\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=\"$cluster\",node=~\"$node\", namespace=~\"$namespace\", resource=\"cpu\"})",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", kubernetes_io_hostname=~\"$node\", namespace=~\"$namespace\", container!=\"\"}[5m]))",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "CPU Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{cluster=\"$cluster\",node=~\"$node\", resource=\"cpu\"})",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=\"$cluster\",node=~\"$node\", namespace=~\"$namespace\", resource=\"cpu\"})",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "CPU Limits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=\"$cluster\",node=~\"$node\", namespace=~\"$namespace\", resource=\"cpu\"})",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "CPU Usage / Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", kubernetes_io_hostname=~\"$node\", namespace=~\"$namespace\", container!=\"\"}[5m])) / sum(kube_node_status_capacity{cluster=\"$cluster\",node=~\"$node\", resource=\"cpu\"})",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "CPU Usage / Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", kubernetes_io_hostname=~\"$node\", namespace=~\"$namespace\", container!=\"\"}[5m])) / sum(kube_pod_container_resource_requests{cluster=\"$cluster\",node=~\"$node\", namespace=~\"$namespace\", resource=\"cpu\"})",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Memory Requests / Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=\"$cluster\",node=~\"$node\", namespace=~\"$namespace\", resource=\"cpu\"}) / sum(kube_node_status_capacity{cluster=\"$cluster\",node=~\"$node\", resource=\"cpu\"})",
     "legendFormat": "requests"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Node Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{cluster=\"$cluster\", kubernetes_io_hostname=~\"$node\", namespace=~\"$namespace\", container!=\"\"})",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(kube_node_status_capacity{cluster=\"$cluster\",node=~\"$node\", resource=\"memory\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=\"$cluster\",node=~\"$node\", namespace=~\"$namespace\", resource=\"memory\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=\"$cluster\",node=~\"$node\", namespace=~\"$namespace\", resource=\"memory\"})",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{cluster=\"$cluster\", kubernetes_io_hostname=~\"$node\", namespace=~\"$namespace\", container!=\"\"})",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Memory Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{cluster=\"$cluster\",node=~\"$node\", resource=\"memory\"})",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=\"$cluster\",node=~\"$node\", namespace=~\"$namespace\", resource=\"memory\"})",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Memory Limits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=\"$cluster\",node=~\"$node\", namespace=~\"$namespace\", resource=\"memory\"})",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Memory Usage / Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{cluster=\"$cluster\", kubernetes_io_hostname=~\"$node\", namespace=~\"$namespace\", container!=\"\"}) / sum(kube_node_status_capacity{cluster=\"$cluster\",node=~\"$node\", resource=\"memory\"})",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Memory Usage / Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{cluster=\"$cluster\", kubernetes_io_hostname=~\"$node\", namespace=~\"$namespace\", container!=\"\"}) / sum(kube_pod_container_resource_requests{cluster=\"$cluster\",node=~\"$node\", namespace=~\"$namespace\", resource=\"memory\"})",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Memory Requests / Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=\"$cluster\",node=~\"$node\", namespace=~\"$namespace\", resource=\"memory\"}) / sum(kube_node_status_capacity{cluster=\"$cluster\",node=~\"$node\", resource=\"memory\"})",
     "legendFormat": "requests"
    }
   ]
  },
  { "title": "Pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "# of Running Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\", cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# of Succeeded Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Succeeded\", cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# of Pending Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\", cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# of Failed Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\", cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}