{
 "title": "OTel Java Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "deployment_environment_name",
    "label": "deployment_environment_name",
    "query": {
     "query": "label_values(target_info{telemetry_sdk_language=\"java\"},deployment_environment_name)"
    }
   },
   {
    "name": "k8s_cluster_name",
    "label": "k8s_cluster_name",
    "query": {
     "query": "label_values(target_info{telemetry_sdk_language=\"java\"},k8s_cluster_name)"
    }
   },
   {
    "name": "k8s_namespace_name",
    "label": "k8s_namespace_name",
    "query": {
     "query": "label_values(target_info{k8s_cluster_name=~\"$k8s_cluster_name\", telemetry_sdk_language=\"java\"},k8s_namespace_name)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(target_info{deployment_environment_name=~\"$deployment_environment_name\", k8s_cluster_name=~\"$k8s_cluster_name\", k8s_namespace_name=~\"$k8s_namespace_name\", telemetry_sdk_language=\"java\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(target_info{deployment_environment_name=~\"$deployment_environment_name\", k8s_cluster_name=~\"$k8s_cluster_name\", k8s_namespace_name=~\"$k8s_namespace_name\", job=\"$job\", telemetry_sdk_language=\"java\"},instance)"
    }
   },
   { "name": "percentile", "label": "percentile", "query": "0.95,0.5,0.9,0.99" },
   {
    "name": "heap_pool_name",
    "label": "heap_pool_name",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{job=~\"$job\", instance=~\"$instance\", jvm_memory_type=\"heap\"},jvm_memory_pool_name)"
    }
   },
   {
    "name": "non_heap_pool_name",
    "label": "non_heap_pool_name",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{job=~\"$job\", instance=~\"$instance\", jvm_memory_type=\"non_heap\"},jvm_memory_pool_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "JVM Version",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by(process_runtime_name, process_runtime_version, process_runtime_description) (target_info{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jvm_cpu_recent_utilization_ratio{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sum(jvm_memory_used_bytes{job=~\"$job\", instance=~\"$instance\", jvm_memory_type=\"heap\"}) by (instance) / sum(jvm_memory_limit_bytes{job=~\"$job\", instance=~\"$instance\", jvm_memory_type=\"heap\"}) by (instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non-Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sum(jvm_memory_used_bytes{job=~\"$job\", instance=~\"$instance\", jvm_memory_type=\"non_heap\"}) by (instance) / sum(jvm_memory_limit_bytes{job=~\"$job\", instance=~\"$instance\", jvm_memory_type=\"non_heap\"}) by (instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sum (jvm_thread_count{job=~\"$job\", instance=~\"$instance\"}) by (instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocked Threads",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jvm_thread_count{job=~\"$job\", instance=~\"$instance\", jvm_thread_state=\"blocked\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Classes Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sum (jvm_class_count{job=~\"$job\", instance=~\"$instance\"}) by (instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Heap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(jvm_memory_used_bytes{job=~\"$job\", instance=~\"$instance\", jvm_memory_type=\"heap\"}) by (jvm_memory_pool_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used NonHeap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(jvm_memory_used_bytes{job=~\"$job\", instance=~\"$instance\", jvm_memory_type=\"non_heap\"}) by (jvm_memory_pool_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(jvm_cpu_time_seconds_total{job=~\"$job\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(sum(jvm_memory_used_bytes{job=~\"$job\", instance=~\"$instance\"}) by (instance))",
     "legendFormat": "usage(jvm)"
    }
   ]
  },
  { "title": "RED Metrics (Server)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "60 * sum by (http_response_status_code) (rate(http_server_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(http_server_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance\", http_response_status_code=~\"5.+\"}[5m])) / on(instance) sum by(instance) (rate(http_server_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(histogram_quantile($percentile, sum by(le, http_response_status_code) (rate(http_server_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[5m]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RED Metrics (Client)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "targets": [
      {
       "expr": "60 * sum(rate(http_client_requests_seconds_count{app=~\"$app\", cluster=~\"$cluster\", instance=~\"$instance\", pod=~\"$pod\"}[5m])) by (outcome)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(http_client_requests_seconds_count{app=~\"$app\", cluster=~\"$cluster\", instance=~\"$instance\", pod=~\"$pod\", status=~\"5..\"}[5m])) by (status) / sum(rate(http_client_requests_seconds_count{app=~\"$app\", cluster=~\"$cluster\", instance=~\"$instance\", pod=~\"$pod\"}[5m])) by (status) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum(rate(http_client_requests_seconds_bucket{app=~\"$app\", cluster=~\"$cluster\", instance=~\"$instance\", pod=~\"$pod\"}[5m])) by (le, outcome))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Usage ($heap_pool_name)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
     "repeat": "heap_pool_name",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(jvm_memory_used_bytes{job=~\"$job\", instance=~\"$instance\", jvm_memory_pool_name=\"$heap_pool_name\"})",
       "legendFormat": "used"
      },
      {
       "expr": "avg(jvm_memory_committed_bytes{job=~\"$job\", instance=~\"$instance\", jvm_memory_pool_name=\"$heap_pool_name\"})",
       "legendFormat": "commited"
      },
      {
       "expr": "avg(jvm_memory_limit_bytes{job=~\"$job\", instance=~\"$instance\", jvm_memory_pool_name=\"$heap_pool_name\"})",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Non-Heap Usage ($non_heap_pool_name)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
     "repeat": "non_heap_pool_name",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(jvm_memory_used_bytes{job=~\"$job\", instance=~\"$instance\", jvm_memory_pool_name=~\"$non_heap_pool_name\"})",
       "legendFormat": "used"
      },
      {
       "expr": "avg(jvm_memory_committed_bytes{job=~\"$job\", instance=~\"$instance\", jvm_memory_pool_name=~\"$non_heap_pool_name\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "avg(jvm_memory_limit_bytes{job=~\"$job\", instance=~\"$instance\", jvm_memory_pool_name=~\"$non_heap_pool_name\"})",
       "legendFormat": "limit"
      }
     ]
    }
   ]
  },
  {
   "title": "GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Pause Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg by(jvm_gc_name, jvm_gc_action) (irate(jvm_gc_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}[5m]))",
       "legendFormat": "{{jvm_gc_name}} [{{jvm_gc_action}}]"
      }
     ]
    },
    {
     "title": "GC Pause Duration",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(jvm_gc_name, jvm_gc_action) (irate(jvm_gc_duration_seconds_sum{job=~\"$job\", instance=~\"$instance\"}[5m]))",
       "legendFormat": "{{jvm_gc_name}} [ {{jvm_gc_action}} ]"
      }
     ]
    }
   ]
  }
 ]
}