{
 "title": "Spring Boot Dashboard",
 "description": "request rate, error rate, duration",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "app",
    "label": "app",
    "query": {
     "query": "label_values(application_ready_time_seconds,app)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(application_ready_time_seconds{app=\"$app\"},cluster)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values({cluster=~\"$cluster\", app=\"$app\"},pod)"
    }
   },
   {
    "name": "region",
    "query": {
     "query": "label_values(application_ready_time_seconds{app=\"$app\"},region)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(application_ready_time_seconds{app=\"$app\", region=~\"$region\"},instance)"
    }
   },
   { "name": "percentile", "label": "percentile", "query": "0.95,0.5,0.9,0.99" },
   {
    "name": "heap_id",
    "label": "Heap ID",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{app=\"$app\", area=\"heap\"},id)"
    }
   },
   {
    "name": "nonheap_id",
    "label": "Non-Heap ID",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{app=\"$app\", area=\"nonheap\"},id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(process_uptime_seconds{app=~\"$app\", cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "min(process_uptime_seconds{app=~\"$app\", region=~\"$region\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(process_cpu_usage{app=~\"$app\", cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(process_cpu_usage{app=~\"$app\", region=~\"$region\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Load (1m)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(system_load_average_1m{app=~\"$app\", cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(system_load_average_1m{app=~\"$app\", region=~\"$region\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocked Threads",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jvm_threads_states_threads{app=~\"$app\", cluster=~\"$cluster\", pod=~\"$pod\", state=\"blocked\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(jvm_threads_states_threads{app=~\"$app\", region=~\"$region\", instance=~\"$instance\", state=\"blocked\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sum(jvm_memory_used_bytes{app=~\"$app\", cluster=~\"$cluster\", pod=~\"$pod\", area=\"heap\"}) by (pod) / sum(jvm_memory_max_bytes{app=~\"$app\", cluster=~\"$cluster\", pod=~\"$pod\", area=\"heap\"}) by (pod))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(sum(jvm_memory_used_bytes{app=~\"$app\", region=~\"$region\", instance=~\"$instance\", area=\"heap\"}) by (instance) / sum(jvm_memory_max_bytes{app=~\"$app\", region=~\"$region\", instance=~\"$instance\", area=\"heap\"}) by (instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non-Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sum(jvm_memory_used_bytes{app=~\"$app\", cluster=~\"$cluster\", pod=~\"$pod\", area=\"nonheap\"}) by (pod) / sum(jvm_memory_max_bytes{app=~\"$app\", cluster=~\"$cluster\", pod=~\"$pod\", area=\"nonheap\"}) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Heap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(jvm_memory_used_bytes{app=~\"$app\", cluster=~\"$cluster\", pod=~\"$pod\", area=\"heap\"}) by (id)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(jvm_memory_used_bytes{app=~\"$app\", region=~\"$region\", instance=~\"$instance\", area=\"heap\"}) by (id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used NonHeap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(jvm_memory_used_bytes{app=~\"$app\", cluster=~\"$cluster\", pod=~\"$pod\", area=\"nonheap\"}) by (id)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(jvm_memory_used_bytes{app=~\"$app\", region=~\"$region\", instance=~\"$instance\", area=\"nonheap\"}) by (id)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RED Metrics (Server)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "60 * sum(rate(http_server_requests_seconds_count{app=~\"$app\", cluster=~\"$cluster\", pod=~\"$pod\"}[5m])) by (outcome)",
     "legendFormat": "__auto"
    },
    {
     "expr": "60 * sum(rate(http_server_requests_seconds_count{app=~\"$app\", region=~\"$region\", instance=~\"$instance\"}[5m])) by (outcome)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{app=~\"$app\", cluster=~\"$cluster\", pod=~\"$pod\", status=~\"5..\"}[5m])) by (status) / sum(rate(http_server_requests_seconds_count{app=~\"$app\", cluster=~\"$cluster\", pod=~\"$pod\"}[5m])) by (status) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{app=~\"$app\", region=~\"$region\", instance=~\"$instance\", status=~\"5..\"}[5m])) by (status) / sum(rate(http_server_requests_seconds_count{app=~\"$app\", region=~\"$region\", instance=~\"$instance\"}[5m])) by (status) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(http_server_requests_seconds_bucket{app=~\"$app\", cluster=~\"$cluster\", pod=~\"$pod\"}[5m])) by (le, outcome))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile($percentile, sum(rate(http_server_requests_seconds_bucket{app=~\"$app\", region=~\"$region\", instance=~\"$instance\"}[5m])) by (le, outcome))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RED Metrics (Client)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "targets": [
      {
       "expr": "60 * sum(rate(http_client_requests_seconds_count{app=~\"$app\", cluster=~\"$cluster\", pod=~\"$pod\"}[5m])) by (outcome)",
       "legendFormat": "__auto"
      },
      {
       "expr": "60 * sum(rate(http_client_requests_seconds_count{app=~\"$app\", region=~\"$region\", instance=~\"$instance\"}[5m])) by (outcome)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(http_client_requests_seconds_count{app=~\"$app\", cluster=~\"$cluster\", pod=~\"$pod\", status=~\"5..\"}[5m])) by (status) / sum(rate(http_client_requests_seconds_count{app=~\"$app\", cluster=~\"$cluster\", pod=~\"$pod\"}[5m])) by (status) ",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(http_client_requests_seconds_count{app=~\"$app\", region=~\"$region\", instance=~\"$instance\", status=~\"5..\"}[5m])) by (status) / sum(rate(http_client_requests_seconds_count{app=~\"$app\", region=~\"$region\", instance=~\"$instance\"}[5m])) by (status) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum(rate(http_client_requests_seconds_bucket{app=~\"$app\", cluster=~\"$cluster\", pod=~\"$pod\"}[5m])) by (le, outcome))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile($percentile, sum(rate(http_client_requests_seconds_bucket{app=~\"$app\", region=~\"$region\", instance=~\"$instance\"}[5m])) by (le, outcome))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Heap Usage ($heap_id)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "repeat": "heap_id",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(jvm_memory_used_bytes{app=~\"$app\", cluster=~\"$cluster\", pod=~\"$pod\", id=\"$heap_id\"})",
     "legendFormat": "used"
    },
    {
     "expr": "avg(jvm_memory_committed_bytes{app=~\"$app\", cluster=~\"$cluster\", pod=~\"$pod\", id=\"$heap_id\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "avg(jvm_memory_max_bytes{app=~\"$app\", cluster=~\"$cluster\", pod=~\"$pod\", id=\"$heap_id\"})",
     "legendFormat": "max"
    },
    {
     "expr": "avg(jvm_memory_used_bytes{app=~\"$app\", region=~\"$region\", instance=~\"$instance\", id=\"$heap_id\"})",
     "legendFormat": "used"
    },
    {
     "expr": "avg(jvm_memory_committed_bytes{app=~\"$app\", region=~\"$region\", instance=~\"$instance\", id=\"$heap_id\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "avg(jvm_memory_max_bytes{app=~\"$app\", region=~\"$region\", instance=~\"$instance\", id=\"$heap_id\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Non-Heap Usage ($nonheap_id)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "repeat": "nonheap_id",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(jvm_memory_used_bytes{app=~\"$app\", cluster=~\"$cluster\", pod=~\"$pod\", id=\"$nonheap_id\"})",
     "legendFormat": "used"
    },
    {
     "expr": "avg(jvm_memory_committed_bytes{app=~\"$app\", cluster=~\"$cluster\", pod=~\"$pod\", id=\"$nonheap_id\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "avg(jvm_memory_max_bytes{app=~\"$app\", cluster=~\"$cluster\", pod=~\"$pod\", id=\"$nonheap_id\"})",
     "legendFormat": "max"
    },
    {
     "expr": "avg(jvm_memory_used_bytes{app=~\"$app\", region=~\"$region\", instance=~\"$instance\", id=\"$nonheap_id\"})",
     "legendFormat": "used"
    },
    {
     "expr": "avg(jvm_memory_committed_bytes{app=~\"$app\", region=~\"$region\", instance=~\"$instance\", id=\"$nonheap_id\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "avg(jvm_memory_max_bytes{app=~\"$app\", region=~\"$region\", instance=~\"$instance\", id=\"$nonheap_id\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Pause Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg(irate(jvm_gc_pause_seconds_count{app=~\"$app\", cluster=~\"$cluster\", pod=~\"$pod\"}[5m])) by (gc, action, cause)",
       "legendFormat": "{{gc}} {{action}} [{{cause}}]"
      },
      {
       "expr": "avg(irate(jvm_gc_pause_seconds_count{app=~\"$app\", region=~\"$region\", instance=~\"$instance\"}[5m])) by (gc, action, cause)",
       "legendFormat": "{{gc}} {{action}} [{{cause}}]"
      }
     ]
    },
    {
     "title": "GC Pause Duration",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(irate(jvm_gc_pause_seconds_sum{app=~\"$app\", cluster=~\"$cluster\", pod=~\"$pod\"}[5m])) by (gc, action, cause)",
       "legendFormat": "{{gc}} {{action}} [{{cause}}]"
      },
      {
       "expr": "avg(irate(jvm_gc_pause_seconds_sum{app=~\"$app\", region=~\"$region\", instance=~\"$instance\"}[5m])) by (gc, action, cause)",
       "legendFormat": "{{gc}} {{action}} [{{cause}}]"
      }
     ]
    }
   ]
  }
 ]
}