#@ load("@ytt:data", "data")
apiVersion: v1
kind: Service
metadata:
  name: blog-frontend
  namespace: blog
  annotations:
    kapp.k14s.io/change-group: workload
  labels:
    app: blog-frontend
    app.kubernetes.io/part-of: blog-frontend
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: blog-frontend
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-frontend
  namespace: blog
  annotations:
    kapp.k14s.io/change-group: workload
  labels:
    app: blog-frontend
    app.kubernetes.io/part-of: blog-frontend
spec:
  replicas: #@ data.values.replicas
  selector:
    matchLabels:
      app: blog-frontend
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
        github.com/revision: #@ data.values.git_revision
      labels:
        app: blog-frontend
        app.kubernetes.io/part-of: blog-frontend
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -XX:ActiveProcessorCount=2 -Dfile.encoding="UTF-8" -Dmanagement.endpoint.health.probes.add-additional-paths="true" -Dmanagement.endpoint.health.show-details="always" -Dmanagement.endpoints.web.base-path="/actuator" -Dmanagement.endpoints.web.exposure.include="*" -Dmanagement.health.probes.enabled="true" -Dmanagement.server.port="8081" -Dserver.port="8080" -Duser.country="JP" -Duser.language="ja" -Duser.timezone="Asia/Tokyo"
        - name: BPL_JVM_THREAD_COUNT
          value: "28"
        - name: spring.security.oauth2.client.registration.google.client-id
          valueFrom:
            secretKeyRef:
              name: frontend-config
              key: oauth2-google-client-id
        - name: spring.security.oauth2.client.registration.google.client-secret
          valueFrom:
            secretKeyRef:
              name: frontend-config
              key: oauth2-google-client-secret
        - name: logging.structured.format.console
          value: ecs
        - name: info.env.hostname
          value: ${HOSTNAME:}
        - name: blog-api.url
          value: http://blog-api.blog.svc.cluster.local
        - name: comment-api.url
          value: http://comment-api.blog.svc.cluster.local
        - name: note-api.url
          value: http://note-api.note.svc.cluster.local
        - name: counter-api.url
          value: http://counter-api.blog.svc.cluster.local/counter
        - name: counter-api.ip-black-list
          value: #@ ",".join(data.values.ip_blacklist)
        - name: management.otlp.logging.endpoint
          value: http://otel-collector.opentelemetry.svc.cluster.local:4318/v1/logs
        - name: management.otlp.tracing.endpoint
          value: http://otel-collector.opentelemetry.svc.cluster.local:4318/v1/traces
        - name: management.opentelemetry.resource-attributes.k8s.pod.name
          value: ${HOSTNAME:}
        - name: management.opentelemetry.resource-attributes.k8s.node.name
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: management.opentelemetry.resource-attributes.host.ip
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: spring.threads.virtual.enabled
          value: "false"
        image: #@ data.values.image
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /livez
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
            scheme: HTTP
        startupProbe:
          httpGet:
            path: /readyz
            port: 8080
            scheme: HTTP
          failureThreshold: 20
          periodSeconds: 5
        name: workload
        ports:
        - containerPort: 8080
          name: user-port
          protocol: TCP
        resources:
          limits:
            memory: 1024Mi
          requests:
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1002
          seccompProfile:
            type: RuntimeDefault
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: blog-frontend
              topologyKey: kubernetes.io/hostname
            weight: 1
---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-config
  namespace: blog
type: Opaque
stringData:
  oauth2-google-client-id: #@ data.values.oauth2.google.client_id
  oauth2-google-client-secret: #@ data.values.oauth2.google.client_secret