apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: korifi-workloads-ingress-cert
  namespace: korifi
spec:
  dnsNames:
  - "*.apps.cf.ik.am"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: korifi-workloads-ingress-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: korifi-workloads-ingress-cert
  namespace: korifi
spec:
  dnsNames:
  - "*.cf.ik.am"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: korifi-workloads-ingress-cert