#@ load("@ytt:data", "data")
#@ for ns in ["cf", "korifi"]:
---
apiVersion: v1
kind: Secret
metadata:
  name: image-registry-credentials
  namespace: #@ ns
type: kubernetes.io/dockerconfigjson
stringData:
  #@yaml/text-templated-strings
  .dockerconfigjson: |-
    {
      "auths": {
        "(@= data.values.korifi_registry.server @)": {
          "username": "(@= data.values.korifi_registry.username @)",
          "password": "(@= data.values.korifi_registry.password @)"
        }
      }
    }
#@ end