apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: retry
  namespace: traefik
spec:
  retry:
    attempts: 3
    initialInterval: 100ms
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: with-retry-timeout
  namespace: traefik
spec:
  forwardingTimeouts:
    responseHeaderTimeout: 10s