#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.subset({"kind": "Deployment", "metadata": {"name": "traefik"}})
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by=overlay.subset({"name": "traefik"})
      - livenessProbe:
          #@overlay/remove
          httpGet:
          #@overlay/match missing_ok=True
          exec:
            command:
            - sh
            - -c
            - "wget -q -O /tmp/routers http://localhost:8080/api/http/routers && grep -q '\"status\":\"enabled\"' /tmp/routers"
          #@overlay/match missing_ok=True
          initialDelaySeconds: 30
          #@overlay/match missing_ok=True
          periodSeconds: 15
          failureThreshold: 3
          #@overlay/match missing_ok=True
          timeoutSeconds: 5
        #@overlay/match missing_ok=True
        startupProbe:
          exec:
            command:
            - sh
            - -c
            - "wget -q -O /tmp/routers http://localhost:8080/api/http/routers && grep -q '\"status\":\"enabled\"' /tmp/routers"
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 30
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3