apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: k8s-oidc-exposer
  namespace: kube-system
spec:
  virtualhost:
    fqdn: k8s-oidc-exposer.lemon.maki.lol
    tls:
      secretName: projectcontour/default-tls
  routes:
  - services:
    - name: k8s-oidc-exposer
      port: 80