apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: k8s-oidc-exposer
  namespace: kube-system
spec:
  virtualhost:
    fqdn: k8s-oidc-exposer.ik.am
    tls:
      secretName: projectcontour/default-tls-ik-am
  routes:
  - services:
    - name: k8s-oidc-exposer
      port: 80