apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: cert-manager
  namespace: app-install
  annotations:
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order.1: "upsert after upserting regsecret"
    kapp.k14s.io/change-rule.delete-order.1: "delete before deleting regsecret"
spec:
  serviceAccountName: kapp
  fetch:
  - helmChart:
      name: cert-manager
      version: 2.1.8
      repository:
        url: oci://registry.maki.lol/bitnamicharts
        secretRef:
          name: regsecret
  - git:
      url: https://github.com/making/k8s-gitops.git
      ref: origin/main
      subPath: lemon/platform/cert-manager
  syncPeriod: 24h
  template:
  - helmTemplate:
      name: cert-manager
      namespace: cert-manager
      path: "0"
      valuesFrom:
      - path: 1/helm-values.yaml
  - ytt:
      paths:
      - "-"
      - 1/config
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true
      delete:
        #! Force delete PVCs, since StatefulSet does not delete them
        rawOptions:
        - --apply-ignored=true