apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: gemfire-operator
  namespace: app-install
  annotations:
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order.1: "upsert after upserting gemfire-crd"
    kapp.k14s.io/change-rule.delete-order.1: "delete before deleting gemfire-crd"
    kapp.k14s.io/change-rule.create-order.2: "upsert after upserting cert-manager"
    kapp.k14s.io/change-rule.delete-order.2: "delete before deleting cert-manager"
spec:
  serviceAccountName: kapp
  fetch:
  - helmChart:
      name: gemfire-operator
      version: 2.6.1
      repository:
        url: oci://registry.maki.lol/tanzu-gemfire-for-kubernetes
        secretRef:
          name: regsecret
  - git:
      url: https://github.com/making/k8s-gitops.git
      ref: origin/main
      subPath: lemon/platform/gemfire-operator
  syncPeriod: 24h
  template:
  - sops:
      age:
        privateKeysSecretRef:
          name: age-key
  - helmTemplate:
      name: gemfire-operator
      namespace: gemfire-system
      path: "0"
      valuesFrom:
      - path: 1/helm-values.yaml
  - ytt:
      paths:
      - "-"
      - 1/config
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true
      delete:
        #! Force delete PVCs, since StatefulSet does not delete them
        rawOptions:
        - --apply-ignored=true