apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: gemfire-crd
  namespace: app-install
  annotations:
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order.1: "upsert after upserting regsecret"
    kapp.k14s.io/change-rule.delete-order.1: "delete before deleting regsecret"
    kapp.k14s.io/change-rule.create-order.2: "upsert after upserting cert-manager"
    kapp.k14s.io/change-rule.delete-order.2: "delete before deleting cert-manager"
spec:
  serviceAccountName: kapp
  fetch:
  - helmChart:
      name: gemfire-crd
      version: 2.5.0
      repository:
        url: oci://registry.maki.lol/tanzu-gemfire-for-kubernetes
        secretRef:
          name: regsecret
  - git:
      url: https://github.com/making/k8s-gitops.git
      ref: origin/main
      subPath: lemon/platform/gemfire-crd
  syncPeriod: 24h
  template:
  - helmTemplate:
      name: gemfire-crd
      path: "0"
      valuesFrom:
      - path: 1/helm-values.yaml
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=false
      - --diff-mask=true
      delete:
        #! Force delete PVCs, since StatefulSet does not delete them
        rawOptions:
        - --apply-ignored=true