apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: grafana-operator
  namespace: app-install
  annotations:
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order.1: "upsert after upserting contour"
    kapp.k14s.io/change-rule.delete-order.1: "delete before deleting contour"
    kapp.k14s.io/change-rule.create-order.2: "upsert after upserting openldap"
    kapp.k14s.io/change-rule.delete-order.2: "delete before deleting openldap"
spec:
  serviceAccountName: kapp
  fetch:
  - helmChart:
      name: grafana-operator
      version: 4.9.8
      repository:
        url: oci://registry-1.docker.io/bitnamicharts
  - git:
      url: https://github.com/making/k8s-gitops.git
      ref: origin/main
      subPath: lemon/platform/grafana-operator
  syncPeriod: 168h
  template:
  - helmTemplate:
      name: grafana-operator
      namespace: grafana-operator
      path: "0"
      valuesFrom:
      - path: 1/helm-values.yaml
  - ytt:
      paths:
      - "-"
      - 1/config
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true
      delete:
        #! Force delete PVCs, since StatefulSet does not delete them
        rawOptions:
        - --apply-ignored=true