apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: k8s-oidc-exposer
  namespace: app-install
  annotations:
    kapp.k14s.io/change-group: "{name}"
spec:
  serviceAccountName: kapp
  fetch:
  - git:
      url: https://github.com/making/k8s-gitops.git
      ref: origin/main
      subPath: lemon/platform/k8s-oidc-exposer
  - git:
      url: https://github.com/categolj/k8s-oidc-exposer.git
      ref: origin/images
  syncPeriod: 24h
  template:
  - sops:
      age:
        privateKeysSecretRef:
          name: age-key
  - ytt:
      paths:
      - 0/config
      valuesFrom:
      - path: 1/jvm_aarch64.yaml
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true
      delete:
        #! Force delete PVCs, since StatefulSet does not delete them
        rawOptions:
        - --apply-ignored=true