apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: openldap
  namespace: app-install
  annotations:
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order.1: "upsert after upserting contour"
    kapp.k14s.io/change-rule.delete-order.1: "delete before deleting contour"
spec:
  serviceAccountName: kapp
  fetch:
  - helmChart:
      name: openldap-stack-ha
      version: "2.1.6"
      repository:
        url: https://jp-gouin.github.io/helm-openldap
  - git:
      url: https://github.com/making/k8s-gitops.git
      ref: origin/main
      subPath: lemon/platform/openldap
  syncPeriod: 24h
  template:
  - sops:
      age:
        privateKeysSecretRef:
          name: age-key
  - helmTemplate:
      name: openldap-stack-ha
      namespace: openldap
      path: "0"
      valuesFrom:
      - path: 1/helm-values.yaml
      - path: 1/credentials.yaml
  - ytt:
      paths:
      - '-'
      - 1/config
      valuesFrom:
      - path: 1/credentials.yaml
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true
      delete:
        #! Force delete PVCs, since StatefulSet does not delete them
        rawOptions:
        - --apply-ignored=true