apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: binfmt
  namespace: kube-system
spec:
  selector:
    matchLabels: { app: binfmt }
  template:
    metadata:
      labels: { app: binfmt }
    spec:
      initContainers:
      - name: binfmt
        image: tonistiigi/binfmt:qemu-v10.2.1-65
        args: [ "--install", "amd64" ]
        securityContext:
          privileged: true
        volumeMounts:
        - name: binfmt-misc
          mountPath: /proc/sys/fs/binfmt_misc
          mountPropagation: Bidirectional
      containers:
      - name: pause
        image: portainer/pause:3.9
      volumes:
      - name: binfmt-misc
        hostPath:
          path: /proc/sys/fs/binfmt_misc
          type: Directory