apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: metallb
  namespace: app-install
  annotations:
    kapp.k14s.io/change-group: "{name}"
spec:
  serviceAccountName: kapp
  fetch:
  - http:
      url: https://raw.githubusercontent.com/metallb/metallb/v0.15.2/config/manifests/metallb-native.yaml
  - git:
      url: https://github.com/making/k8s-gitops.git
      ref: origin/main
      subPath: apricot/platform/metallb
  syncPeriod: 24h
  template:
  - ytt:
      paths:
      - "0"
      - 1/config
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true
      delete:
        #! Force delete PVCs, since StatefulSet does not delete them
        rawOptions:
        - --apply-ignored=true